### ISSUE TITLE
Not possible to remove emoji 

### ISSUE THREAD

**Issue by knedlsepp** [attzonko/mmpy_bot#100]
It is currently not possible (or documented) to remove emojis sent using e.g.: `message.react("pizza")`

**Comment by attzonko** [comment]
What do you mean by remove the emoji?

**Comment by knedlsepp** [comment]
When reacting to somebody's message, it's possible to add an emoji, just as the above thumbs up. However I couldn't figure out a way to remove this again.

**Comment by attzonko** [comment]
I think I better understand the request. As it stands today there is no way to remove a reaction emoji in mmpy_bot, but the Mattermost API supports removal of reactions.  I am adding this as an enhancement request. Can you give me a better feel for the use case you have in mind? Are you wanting to remove reactions the bot added, or reactions that other users added?

**Comment by attzonko** [comment]
Please test pull request #101 and let me know if it works the way you think it should.

**Comment by knedlsepp** [comment]
My use case is a poll system, where a bot reacts to "#poll: a,b,c" by creating a message that reads:
```
1. a
2. b
3. c
```
and additionally reacts to this message with the emojis 1️⃣2️⃣3️⃣.
People would then click on the emojis to add their votes. After a certain timeout, I would then like to remove the votes that were cast by the bot itself so the absolute numbers are correct and don't include the bot anymore.

Thanks for the PR, I'll take a look!
