### ISSUE TITLE
message.update() does not work as expected

### ISSUE THREAD

**Issue by knedlsepp** [attzonko/mmpy_bot#102]
**Describe the bug**
The message.update() method seems to be broken.

**How To Reproduce**
I'm using the following snippet and expect the message "I'm waiting" to change after two seconds.
```python
@listen_to('hello', re.IGNORECASE)
def hello_reply(message):
    timeout_message = message.send("I'm waiting.")
    import time
    time.sleep(2)
    message.update("Timeout.", timeout_message['id'])
```
However nothing changes. I did look up the API and it seems that a `PUT` should be used for this kind of request: https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts~1%7Bpost_id%7D%2Fput. `mmpy_bot` currently uses a `POST` request.
I did a quick test to try and fix it in https://github.com/knedlsepp/mmpy_bot/commit/2e2ad5064057aa8c6c69088052ac7d07a399436f, but this didn't resolve the issue.

**Comment by seLain** [comment]
hi @knedlsepp , thanks for digging out this issue.

I think the message_id should be attached in PUT request to make it work.
```python
def update_post(self, message_id, user_id, channel_id,
                    message, files=None, pid=""):
        return self.put(
            '/posts/%s' % message_id,
            {
                'id': message_id,
                'message': message,
            })
```
See if it helps :)

**Comment by knedlsepp** [comment]
Thanks for your fast responses to the issues I'm having. Will give this a try today. I was wondering: is there some more verbose logging I can activate or how do you solve these issues?
