### ISSUE TITLE
can send Multiple instructions in one message

### ISSUE THREAD

**Issue by lifeblood** [attzonko/mmpy_bot#107]
can send Multiple instructions in one message

**Comment by attzonko** [comment]
I am sorry I don’t understand the question/comment.  Can you please elaborate what are you doing or trying to do, and what do you expect the outcome to be.

**Comment by CDA-learner** [comment]
> can send Multiple instructions in one message

yes,i have made some changes to load several instruction in one message.
in the dispatcher.py  _on_new_message
    def _on_new_message(self, msgs):
        print('_on_new_message',msgs)
        messages_content = msgs['data']['post']['message'].split('@')[1:]
        for item in messages_content:
            item = '@' + item
            msgs['data']['post']['message'] = item
            print('after convert msgs', msgs)
            if self.ignore(msgs) is True:
                return
            msg = self.filter_text(msgs)
            print('responsed to xxxx')
            if self.is_mentioned(msg) or self.is_personal(msg):
                self._pool.add_task(('respond_to', msg))
            else:
                self._pool.add_task(('listen_to', msg))
