### ISSUE TITLE
what is bot email and where to create mmpy_bot_settings.py

### ISSUE THREAD

**Issue by at4446** [attzonko/mmpy_bot#110]
Hi All,

I have two questions:
In mattermost I just created a bot but it did not require any email. ALl it asked was name and at the end it gave me a token so what should I place for bot_email?

where do I create the mmpy_bot_settings.py file?

**Comment by attzonko** [comment]
If you supply a token you don't need to have the email to login.

**Comment by at4446** [comment]
@attzonko thank you.
I provided the email address I signed up with for mattermost and my password and it was running and gave me 201 status but I get no response in matter most when I type "bot" or "bot help" or  "hello bot"

**Comment by attzonko** [comment]
Did you add the bot account to the team?

**Comment by at4446** [comment]
@attzonko  yes I have added.
So I crated a bot called "test2" and my mmpy_bot_settings mmpy_bot looks like 

DEBUG = True
BOT_URL = 'http://172.19.0.2:8065/api/v4'
BOT_LOGIN = 'myusername@test.com'
BOT_PASSWORD = '12345'
BOT_TEAM = 'test'

after running MATTERMOST_BOT_SETTINGS_MODULE=mmpy_bot_settings mmpy_bot I get 201 and the scripts runs but nothing happens when I call the bot! also i have no incomoing or outgoing webhooks!

**Comment by attzonko** [comment]
So it sounds like you created a bot account, and you have the token that was generated. You should have your settings as following:
```
BOT_URL = 'http://example.com/api/v4' 
BOT_LOGIN = 'botusername'
BOT_PASSWORD = None
BOT_TOKEN = "theactualtokenyougotwhenyoucreatedthebotaccount" 

```

**Comment by at4446** [comment]
I have the following but I get 
DEBUG = True
BOT_URL = 'http://172.19.0.2:8065/api/v4'
BOT_LOGIN = 'test'
BOT_TOKEN = 'cgk6ftcdpifei884dz1yhzd3fo'
BOT_TEAM = 'test'

![image](https://user-images.githubusercontent.com/15878365/62888292-f2117b80-bd0c-11e9-8e9a-17b4ec1ea6bf.png)

**Comment by attzonko** [comment]
This looks like the bot is up and running. What is the error you see?

**Comment by at4446** [comment]
I created a new bot and it is running now!

**Comment by at4446** [comment]
@attzonko Trying to edit the responses in hello.py
nothing seems to be changed when I change the response of the bot for example from "hello_sender" to "Hello_sender_2". I have tried many ways but no luck anything I am missing here?

This is the path to the file:
my-bot/venv/lib/python2.7/site-packages/mmpy_bot/plugins/hello.py
