### ISSUE TITLE
AttributeError: 'module' object has no attribute 'urllib3'

### ISSUE THREAD

**Issue by mlmnetcologne** [attzonko/mmpy_bot#113]
**Describe the bug**
`Traceback (most recent call last):
  File "/bin/mmpy_bot", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/mmpy_bot/cli.py", line 17, in main
    b = bot.Bot()
  File "/usr/lib/python2.7/site-packages/mmpy_bot/bot.py", line 31, in __init__
    settings.WS_ORIGIN)
  File "/usr/lib/python2.7/site-packages/mmpy_bot/mattermost.py", line 200, in __init__
    self.api = MattermostAPI(url, ssl_verify, token)
  File "/usr/lib/python2.7/site-packages/mmpy_bot/mattermost.py", line 21, in __init__
    requests.packages.urllib3.disable_warnings(
AttributeError: 'module' object has no attribute 'urllib3'`

I have SSL_Verify disabled (False) because I have certificate problems. 
MMPY will not start.

**How To Reproduce**
run mmpy
WEBHOOK_ID = 'ner9...f3ad'
and other normal settings.

**Expected behavior**
mmpy started

**Operating Environment (please complete the following information):**
 - OS: Oracle Linux
 - Python Version: 2.7
 - Mattermost Version: 5.10.0
 - mmpy_bot Version: mmpy_bot-1.3.4-py2.py3-none-any.whl

Hopefully, you can work with that and can help me.

**Comment by attzonko** [comment]
My best guess is that you are using a version of requests that is missing the urllib3 module. Can you share what version of the requests package you are using?

**Comment by mlmnetcologne** [comment]
I have two, 19 and 21. 
That was a problem while installing, I'm now testing on a different environment.

**Comment by mlmnetcologne** [comment]
Jup, changed the envi, now it works, the installation seems this time better. 
The Problem is that the Oracle System setup is bad, and the request package can't be updated.
