### ISSUE TITLE
Table formatting not working with listen_to in a channel

### ISSUE THREAD

**Issue by andylittle** [attzonko/mmpy_bot#115]
Mattermost v5.15.0
Name: mmpy-bot Version: 1.3.4
CentOS Linux release 7.6.1810 (Core

The "@@andy" which is returned with the listen_to may be breaking the format. I did try a blank line at the start of the payload string.

Direct message with bot:
![image](https://user-images.githubusercontent.com/12177246/65643598-f33df580-dfa6-11e9-86fd-745f240679ae.png)

In a channel:
![image](https://user-images.githubusercontent.com/12177246/65643620-02bd3e80-dfa7-11e9-8ea5-cb0d4daa7544.png)

The bot code:

    # -*- encoding: utf-8 -*-
    from mmpy_bot.bot import respond_to, listen_to
    @respond_to('^!test$')
    @listen_to('^!test$')
    def help_request(message):
         payload = """ | Component  | Tests Run   | Tests Failed                      | 
                  |:-----------|:-----------:|:-----------------------------------------------|
                  | Server     | 948         | :white_check_mark: 0|
                  | Web Client | 123         | :warning: 2 [(see details)](http://linktologs) |
                  | iOS Client | 78          | :warning: 3 [(see details)](http://linktologs) | """
        message.reply(payload)

Andy

**Comment by attzonko** [comment]
I wonder if this is somehow related to the new bot account changes in the newer versions of Mattermost. Are you using a bot account? I am assuming @andy is your normal user? I wonder why that is being added to the payload. I'll try to reproduce it and look into it when I have some time. Thanks for bringing it up.

**Comment by andylittle** [comment]
Thanks for your help, if you need anything more tested let me know. @andy is my normal user yes. Coolbot is the bot user name. We just started using the bot around 5.13 or so, I do not know about the older versions of mattermost behavior with the bot.

    BOT_URL = 'http://IP:PORT/api/v4'  # with 'http://' and with '/api/v4' path  
    BOT_LOGIN = 'xxxxxx@xxxx.com'
    BOT_PASSWORD = 'xxxxxx'
    BOT_TEAM = 'xxx-xxx'
    SSL_VERIFY = False
    PLUGINS = [
        'mmpy_bot.plugins', 'plugins',
    ]

**Comment by andylittle** [comment]
json from wireshark capture of working and non working
```json
{"channel_id": "k4fa13s9ui8s5ymy6zpuuyrmja", "message": "@@andy:  | Component  | Tests Run   | Tests Failed                      | \n                  |:-----------|:-----------:|:-----------------------------------------------|\n                  | Server     | 948         | :white_check_mark: 0|\n                  | Web Client | 123         | :warning: 2 [(see details)](http://linktologs) |\n                  | iOS Client | 78          | :warning: 3 [(see details)](http://linktologs) | ", "file_ids": [], "root_id": "", "props": {}}


{"channel_id": "73q3szjrgpbx7exkozhp16gich", "message": " | Component  | Tests Run   | Tests Failed                      | \n                  |:-----------|:-----------:|:-----------------------------------------------|\n                  | Server     | 948         | :white_check_mark: 0|\n                  | Web Client | 123         | :warning: 2 [(see details)](http://linktologs) |\n                  | iOS Client | 78          | :warning: 3 [(see details)](http://linktologs) | ", "file_ids": [], "root_id": "", "props": {}}
```

**Comment by attzonko** [comment]
Ok I had a chance to look at your issue. Actually the bot seems to be working as expected. The message.reply() method is intended to reply to the user who engaged with the bot, hence why it is including `@andy` at the start (not really sure why you see two `@@`, I only see a single one when I tested)

To achieve what you want you can try using the message.send() method.

**Comment by andylittle** [comment]
Yes that fixed it. Thanks
