### ISSUE TITLE
listen to reactions

### ISSUE THREAD

**Issue by fculpo** [attzonko/mmpy_bot#116]
We have a fun need of sending a kick command if a message gets a fixed number of a defined reaction (let's say hammer)

I don't see any get_reaction method, is there a way to do this already ?

**Comment by attzonko** [comment]
Do you mean kick the user out of the channel? Hilarious

**Comment by fculpo** [comment]
well...yes
The point is to listen to reactions though, the resulting action could be anything

**Comment by attzonko** [comment]
You are correct, currently mmpy_bot does not utilize the  /posts/{post_id}/reactions to get a list of reactions to a post. I'll set this as an enhancement request. 

You are welcome to contrinute, or at least help me define how you would expect to utilize a message.get_reactions() method. What would you expect it to return? The same list as the actual Mattermost API reference, or something simpler?

**Comment by fculpo** [comment]
I would keep it simple for now and return what API returns, at least in the first iteration.
The actual "kick" plugin will be doing the intelligent work

**Comment by fculpo** [comment]
loop should thus listen to reaction_added ws event

https://github.com/attzonko/mmpy_bot/blob/182d76951bfa6bbc8d7ef43941110ceb1f15e832/mmpy_bot/dispatcher.py#L131

**Comment by attzonko** [comment]
With Version 2.x of mmpy_bot, you are a lot closer to the MM API, so this should be a lot easier to do now.

**Comment by jneeven** [comment]
To add to this: the way you would do this is subclass the EventHandler so it checks not only for post events but also for reactions. You'd then probably want to add a new decorator like `listen_reaction` or something to register handlers for that. You can basically take all the code we currently use to listen for messages and modify it to fit reactions instead. If anyone implements this, I'd be happy to make this an official feature!
