### ISSUE TITLE
Rename to create new pypi package?

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#12]
Hey @seLain , what do you think about renaming this repo to be able to release to pypi as a new package. I was thinking that we can remove v3 support completely and push a new pypi package which only supports v4.

Name proposal: `mmpy_bot`

Thoughts?

**Comment by seLain** [comment]
I like the idea of removing v3 support. It will definitely make the code easier to maintain. Too bad we can not continue to use the package name `mattermost_bot`. Nevertheless the new name is simple and clear to me. :smiley:

**Comment by attzonko** [comment]
Ok I’ll try and put together a PR for the rename. Are you ok if I put your email in the Authors file for the new package?

On Feb 14, 2018, at 11:50 PM, seLain <notifications@github.com> wrote:

I like the idea of removing v3 support. It will definitely make the code easier to maintain. Too bad we can not continue to use the package name mattermost_bot. Nevertheless the new name is simple and clear to me. 😃

**Comment by seLain** [comment]
Sounds cool. But I had no experience being author of any PyPI package. Will that be an issue ? What responsibility should I take ?

**Comment by attzonko** [comment]
I was just talking about the Authors.rst file in the repo :)

**Comment by seLain** [comment]
That will be no problem. Thanks ! :grin:

**Comment by NerdSec** [comment]
Hi Guys!

Great work and thank you for keeping this project alive. Really great work. Are there still any plans to create that PyPi package? This would really make for efficient upgrades.

**Comment by attzonko** [comment]
Yes there are still plans :) will find the time to do it ASAP

**Comment by attzonko** [comment]
Ok renaming is done. Here is a link to the pypi package: https://pypi.org/project/mmpy-bot/

next step is to deprecate V3 of the API and improve the maintainability score
