### ISSUE TITLE
[QUESTION] How to send (not .txt) files?

### ISSUE THREAD

**Issue by pinpox** [attzonko/mmpy_bot#122]
Hi,

I can't figure this out: How do I send a arbitrary file to a channel?
I want to post an image (test.png) as a message, but the example in the readme seems to fail for non-txt files. Could you provide me with an example?

**Comment by klobes5** [comment]
@pinpox I was able to get it to work by getting python to treat the file as a binary instead of attempting to decode it. It looks like this: ` file = open('test.png', 'rb')  # need b so that file gets treated as binary instead of decoded as utf-8`
