### ISSUE TITLE
[Feature Request] Extend internal help function for listen_to

### ISSUE THREAD

**Issue by pinpox** [attzonko/mmpy_bot#123]
Hello, 

I have a feature request: The bot responds to `help` with the implemented `respond_to` functions, parsing the documentation string of these. This is very nice, but would it be possible to extend this functionality to `listen_to` functions aswell?

My bot mostly uses `listen_to`, with a defined prefix, e.g. `!mybot <command>`, it would be nice if the help function could show the info for those too.

If you provide me the steps necessary for this, I could try to send a PR.

**Comment by attzonko** [comment]
Take a look at the _default_reply() and docs_reply() functions in dispatcher.py

You can see the logic in there of how the help message is formed. You should be able to extend the functionality to include listen_to commands.

**Comment by jneeven** [comment]
Closed by #153.
