### ISSUE TITLE
Bot name in message is considered as mention, even without @

### ISSUE THREAD

**Issue by keto** [attzonko/mmpy_bot#125]
**Describe the bug**

When a message contains the bot name, even if it's not prefixed with @, the bot is listed in the mentions and that causes the message to get only passed to the "respond_to" handlers.

**How To Reproduce**
Create handler like:

    @listen_to('^echo (.*)')
    def echo(message, text):
        message.reply(text)

With the bot name being 'thebot', on a channel say 'echo thebot ignores this'.

**Expected behavior**

I think the channel messages with mentions should be also passed to the listen_to handlers, as otherwise it can lead to unexpected behavior. For example plugin for logging all messages on a channel would miss some messages if the bot name happens to be some general word.

This can be somewhat worked around by registering the handler to both listen_to and respond_to, but that doesn't feel right :)

**Comment by jneeven** [comment]
Closed by #153, since `needs_mention=False` (the default) will still trigger if the bot is mentioned.
