### ISSUE TITLE
Message attachment support for bot account (non webhook)

### ISSUE THREAD

**Issue by muffetman** [attzonko/mmpy_bot#126]
Hi,

Perhaps this should be directed towards the Mattermost dev team, but first I want to clarify the bahaviour I am seeing is correct.

I am using mmpy_bot successfully for basic messaging, but I want the bot to send Message Attachment payload with interactive buttons. According to the documentation for mmpy_bot this can be achieved by using the reply_webapi() function, which uses a webhook to send the payload. This works, however the problem I see is that because the payload is sent using the webhook bot account and not the actual bot account, and this causes the actual bot account to get confused by what the webhook account has sent. Here is an example transaction:

- Using Direct Message to the bot account, and command is sent to look for something (i.e. !find mydoc)
- The code for the bot uses message.reply_webapi to respond with payload containing interactive button. As expected, the bot uses the webhook to send this payload
- In the MM Direct Message, the webhook bot responds with the interactive button. The bot see this response from the webhook bot and does not understand what it sent, and responds back with "Bad command ..."

Is this the expected behaviour when using message attachments with mmpy_bot? 

Ideally I would like to be able to send the message attachment payload without using the webhook (i.e. the regular message.reply() function), but according to MM documentation on Interactive Buttons: _Mattermost supports interactive message buttons and menus for incoming and outgoing webhooks, custom slash commands, and plugins via actions._ 

So based on this, it seems that it may not be supported by MM to send interactive message buttons directly using a bot account. Is this limitation causing the behaviour I am seeing?

FYI, the bot account was created using an admin account via Integrations -> Bot Accounts. Originally I did not create a webhook for this at all, but after finding that reply_webapi() was not working I created one and assigned it in mmpy_bot_settings.py and that is when I discovered the behaviour detailed above.

**Comment by attzonko** [comment]
What is triggering the non-webhook bot to think it is getting a command? I don't think it is a problem with MM, but rather how mmpy_bot is being used. The way I see it we have two options:
1. SUpport the use case you have by adding logic to mmpy_bot code to ignore, the webhook version of itself.
2. Figure out if your DM to start the activity should go to the webhook bot account instead, or something like that.

I think at the end of the day figuring out how to make #2 work correctly is the right direction. I am not sure we want to hack up the code to add exceptions for a different bot account to be ignored. I think you should figure out why the bot is being triggered by the response from the second bot, and remedy that in your bot.

Does that make sense?

**Comment by muffetman** [comment]
Hi,

I agree #2 would be the right direction to take. I thought about adding some logic into my bot plugin to ignore the messages from the webhook bot, but it just felt a bit hacky. In the end it seems like the only reason I need to involve the webhook bot account is so that my bot can send message attachments. My original idea for my bot was:

1. User looks for item using !find <name>
2. Bot responds with message attachment for each result, and an interactive button called "Add to Library"
3. When that button is click it will simply trigger a message to the bot along the lines of !add <name>, which triggers a function in the bot to add this particular file to the library.

The idea seemed nice, but having to setup two different bot accounts just for this seemed like overkill. I prefer the simplicity of the user just setting up a single bot account for the user to create and retrieve the token. Also it seems that having that interactive button just trigger a message in MM to the bot was not so simple (the integration must be reachable on a URL).

Hopefully in the future MM will allow non-webhook bot accounts to send message attachments, that would at least solve one part of the issue. For now I'll stick with standard non-interactive messages.
