### ISSUE TITLE
No Bot Account Email/Password

### ISSUE THREAD

**Issue by taylorjason** [attzonko/mmpy_bot#127]
I am using MM v5.21 and setting up a bot account there is no username or password.  So what am I supposed to enter in the mmpy_bot_settings?

Also, would I set up an incoming or outgoing webhook for the Webhook ID setting?

**Comment by attzonko** [comment]
You would use the BOT_TOKEN instead of the username/password settings.

To help you decide if you need to specify the WEBHOOK_ID please refer to the docs here:
https://mmpy-bot.readthedocs.io/en/latest/plugins.html#webhook-support.

**Comment by taylorjason** [comment]
Awesome thanks! I missed the section on the webhook. So to clarify when would you use username and password?

**Comment by attzonko** [comment]
One might use username/password if they are still running an older version of MM 😸 Or if they are lazy like me and have not created the new 'bot' accounts and still running with legacy configurations.
