### ISSUE TITLE
Mentions field not filled out when you mention yourself

### ISSUE THREAD

**Issue by thezboe** [attzonko/mmpy_bot#128]
**Describe the bug**
I want to create a command that can list assets for any user:
`list @user`
That works, but then I cannot run that command across my own user:
`list @me`
The mentions field is not filled out, and therefore errors out when I try to access it.

**How To Reproduce**
Mention yourself in a message to the bot, and then verify that the mentions member is missing.

**Expected behavior**
The mentions member should be available and filled out with the user id of my user on Mattermost.

**Comment by unode** [comment]
I don't see a solution to this. If I understand correctly, `mentions` is a value returned by Mattermost server.
If it's not included and should be, a bug report would likely need to be submitted to Mattermost itself.

**Comment by attzonko** [comment]
Looking at this I agree, this framework does not populate the mentions member of the message, the expectation  is that either the driver or Mattermost server should handle it. Since this is only not the case for '@me' I assume they did it on purpose. Feel free to change their mind.
