### ISSUE TITLE
What features need to the bot to be in the Admin group ? 

### ISSUE THREAD

**Issue by BobForCat** [attzonko/mmpy_bot#130]
Hi, 

Could you elaborate the sentence "For use all API(V4.0.0), you need add bot user to system admin group to avoid 403 error." you wrote in the README ?

- it's not mandatory to be in the admin group ? 
- does being (the bot) in the admin group allows to post in any group (public/private) no matter the bot was added in the group or not ? 

Thanks

**Comment by attzonko** [comment]
All that is trying to convey is that certain APIs require the bot account to be part of the system admin group. It is not mandatory, it just depends on which APIs you plan to use.
