### ISSUE TITLE
How to register behavior on bot startup

### ISSUE THREAD

**Issue by unode** [attzonko/mmpy_bot#132]
The plugin initialization code calls the `on_init()` function, if it exists, but since no arguments are passed, there's no context to send a message or connection to access.

What is the recommended way to send or queue a message to be sent to a specific channel or user?

I'd like to register behavior that is initiated by the bot instead of as a response to `@listen_to` or `@respond_to`.
For instance, sending a message when the bot first starts, send a notification, etc.

**Comment by attzonko** [comment]
Great question. The only way I can think of today to possibly do what you ask is to use the scheduling functionality that was added. I am not 100% sure it will meet your needs, but it has the potential.

**Comment by unode** [comment]
I tried using the `schedule` code and it works but I couldn't figure out how to access the connection object.
Is there some global that can be used and is properly initialized by the time the `schedule`r runs the first time?
