### ISSUE TITLE
Remove listing on bad command

### ISSUE THREAD

**Issue by whoo** [attzonko/mmpy_bot#133]
Hi,
Is it possible to remove command listing (or setup or own ?) to avoid 
```
Bad command "test", Here is what I currently know how to do:
```
I cannot find reference into documentation, I try
DEFAULT_REPLY_MODULE = None
DEFAULT_REPLY = None

without success.

regards,
Whoo

**Comment by attzonko** [comment]
It is not currently possible, but I think the functionality could be easily added. Are you interested in contributing to the code base?

**Comment by whoo** [comment]
Hi,
I'm not a great developper, but I'll have a look on source code.

**Comment by attzonko** [comment]
No worries @whoo we all started somewhere. I will help you by reviewing your code changes.

**Comment by whoo** [comment]
Hi Guys,
After reading code... you can override default reply by adding the following in mmpy_bot_settings.py
```
DEFAULT_REPLY = "Default Message" 
```
