### ISSUE TITLE
Initial setting up of BOT

### ISSUE THREAD

**Issue by gov132** [attzonko/mmpy_bot#137]
I created a team,channel and bot in mattermost.
Installed all the required libraries mmpy_bot.

When I try to run the  bot using MATTERMOST_BOT_SETTINGS = mattermost_bot_settings mmpy_bot

I am not able to run the bot .
Mattermost_bot_Settings in not recognizable 

can you briefly explain what should I do inorder to run the bot.

**Comment by attzonko** [comment]
I am really not sure how you were trying to run the bot from your description. Did you follow the deployment steps in the [docs](https://mmpy-bot.readthedocs.io/en/latest/deploy.html)?
