### ISSUE TITLE
Unable to open/submit the interactive dialog form using mmpy_bot plugin

### ISSUE THREAD

**Issue by kkarnam81** [attzonko/mmpy_bot#138]
@attzonko , Hope you ae doing good. We have forked this mmpy_bot python libraries to set up our BOT. We are able to set up the BOT successfully , but when trying to implement the interactive dialog nothing seems to be happening .

1) For example, in the below example when we click on click nothing seems to happening.
 {
  "attachments": [
    {
      "pretext": "This is the attachment pretext.",
      "text": "This is the attachment text.",
      "actions": [
        {
          "id": "message",
          "name": "Ephemeral Message",
          "integration": {
            _**"url": "http://127.0.0.1:7357",**_
            "context": {
              "action": "do_something_ephemeral"
            }
          }
        }, {
          "id": "update",
          "name": "Update",
          "integration": {
            "url": "http://127.0.0.1:7357",
            "context": {
              "action": "do_something_update"
            }
          }
        }
      ]
    }
  ]
}

2) In the below example we are trying to create a interactive dialog, in this example it is mentioned about some token and url.. not sure exactly what those means. when we implemented using some dummy values  using plugin(@listen_to) , nothing is happening in channel.. so basically trying to understand how can we implement(open &submit) the interactive dialog.. any other set up needs to be done along side what already we downloaded from mmpy_bot libraries.. any help is greatly appreciated.. 

{
    **"trigger_id": "<unique ID generated by the server>",**
    **"url": "<URL to send the submitted request to>",**
    "dialog": {
        "callback_id": "<ID specified by the integration to identify the request>",
        "title": "<title of the dialog>",
        "introduction_text": "<Text describing the dialog box content>",
        "elements": ["<Array of UI elements to display in the dialog>"],
        "submit_label": "<label of the button to complete the dialog>",
        "notify_on_cancel": false,
        "state": "<string provided by the integration that will be echoed back with dialog submission>",
    }
}

**Comment by kkarnam81** [comment]
Can someone please help?

**Comment by kkarnam81** [comment]
Not sure where to go for the help, hence closing the case

**Comment by kkarnam81** [comment]
hoping someone can guide?

**Comment by jneeven** [comment]
From the [Mattermost Docs](https://docs.mattermost.com/developer/interactive-dialogs.html#opening-a-dialog):
> To open a dialog, your integration must first receive an HTTP request from the Mattermost server. This request will be triggered by a slash command or an interactive message. It will include a trigger ID.

In the example you provide above, you use ` "url": "http://127.0.0.1:7357"`. Do you actually have any kind of server running at that address? Looks like it exactly matches the one [here](https://docs.mattermost.com/developer/interactive-messages.html#message-buttons), so I assume not. That being said, @attzonko do you think it would be feasible to have the bot also open up a small webserver for this specific purpose? Would be amazing if we could extend the bot with webhook functionality, it would open up a huge range of additional possibilities: slash commands, dialog boxes, maybe even interaction with external tools (i.e. having the bot filter the incoming webhook and then take some action accordingly) 🚀

**Comment by attzonko** [comment]
@jneeven I don't see why not. It should not be too difficult at all to have the bot handle incoming webhooks in addition to watching messages.

**Comment by jneeven** [comment]
@kkarnam81 You can now use interactive dialog forms in the upcoming 2.0 release, see #153. We're still working on updating the documentation etc, but the code is ready to be used if you need it. The code of interest is in `plugins/webhook_example.py`.
