### ISSUE TITLE
mmpy_bot not found

### ISSUE THREAD

**Issue by Dystharia** [attzonko/mmpy_bot#139]
Hello everyone,
I'm not a system admin, but my company still want me to install this, because I'm the only programmer, I directly ran into a problem.
I'm using Ubuntu 18.04, installed mmpy_bot and created my configfile. Now I want to run "MATTERMOST_BOT_SETTINGS_MODULE=mmpy_bot_settings mmpy_bot" but I just get the message "mmpy_bit: command not found"

What do I need to do here?

Greetings

**Comment by attzonko** [comment]
Sorry for not getting back to you on this for a while. The best advice with the info you sent would be to try and follow closely the deployment docs.
