### ISSUE TITLE
Permanent redirect error

### ISSUE THREAD

**Issue by Manoj1229** [attzonko/mmpy_bot#145]
WebSocketBadStatusException: Handshake status 308 Permanent Redirect

Hey!
I am getting permanent redirect error. while trying to run the code

I have provided
bot url - http://own.cloud.mattermost.com/api/v4/sample_bot
bot_login - login ID
bot_password - **********
bot_token - *****************
bot_team - *******

Thanks in advance

**Comment by attzonko** [comment]
My guess is something wrong with your web proxy configuration.

**Comment by attzonko** [comment]
Did you ever figure this out?
