### ISSUE TITLE
No mmpy_bot script, requirements not installed

### ISSUE THREAD

**Issue by dmrlawson** [attzonko/mmpy_bot#151]
**Describe the bug**
`mmpy_bot` script not created, requirements not installed

**How To Reproduce**

1. Create a venv and activate it
2. `pip install mmpy_bot==1.3.8`
3. Look in the vitualenv's `bin` directory
4. Run `pip freeze`

**Expected behavior**
Pip should install the third party requirements and an `mmpy_bot` script should be created

**Operating Environment (please complete the following information):**
 - OS: Linux
 - Python Version: 3.8.5
 - Mattermost Version: n/a
 - mmpy_bot Version: 1.3.8
 

Thanks very much for the recent release. I encountered the above problem when upgrading so I think something has changed with the packaging perhaps? The documentation suggests that there should still be a `mmpy_bot` script at least.

**Comment by attzonko** [comment]
Re-opening until this is truly sorted out. So @rwky changed the build back to setuptools, which unfortunately has the side effect of replacing the underscore in the package name with a dash. With version 1.3.5+ I was trying to switch over to using flit as the build/publish tool for the pypi package 😞 So with 1.3.9 you will need to use `pip install mmpy-bot==1.3.9`

**Comment by attzonko** [comment]
151
