### ISSUE TITLE
2.0.0 release

### ISSUE THREAD

**Issue by jneeven** [attzonko/mmpy_bot#156]
Let's use this issue to keep track of the to-do list for the upcoming 2.0.0 release. Now that the current version lives on its own branch, we should be able to merge #153 into master and then work from there.

To do:
- [x] Update all documentation
- [x] Let the `Settings` class try to infer values from environment variables if present
- [x] Provide a docker image with an entrypoint that can easily be overridden to add custom plugins etc.
- [ ] Add migration guide to docs
- [ ] Improve logging (it would be nice if the bot facilitates easily logging to file, and the logs should be more extensive with messages of various logging levels)

At release time:
- [x] Publish the docker image as `mmpy_bot:2.0.0`.
- [x] Publish new PyPi package `mmpy_bot:2.0.0`

**Comment by attzonko** [comment]
Agreed, I'll merge #153 with the version as 2.0.0.dev1 and once we finish this todo list we can make it the official 2.0.0 and release to pypi.

**Comment by ttuffin** [comment]
In regards to the documentation, how do we feel update updating README.md to cut out everything south of the "Run the bot" section? I think the information about plugins, attachments and files can be covered in ./docs/.

**Comment by unode** [comment]
Replace that with links to specific sections in the docs? Much shorter, same effect.

**Comment by jneeven** [comment]
Yes, good idea. The example plugins are already a showcase of the functionality, so we can just link to those and add a kind of table of contents that links to each of the doc sections :+1:

The "Run the bot" section needs a little update, but I hope to take care of the environment settings and docker image tomorrow and will then update that part.

**Comment by attzonko** [comment]
@jneeven I published 2.0.0 to pypi.org Please Publish your docker image and close this. We can add more logging and migration docs as part of the next release?

**Comment by jneeven** [comment]
> @jneeven I published 2.0.0 to pypi.org Please Publish your docker image and close this. We can add more logging and migration docs as part of the next release?

I do think it's best to have those migration docs with this current release; providing them one release down the line wouldn't make them very useful. But we can probably update the docs any time without triggering a new release, and since you've already published 2..0.0 I'll push the docker image :+1:

**Comment by jneeven** [comment]
[Done](https://hub.docker.com/layers/jneeven/mmpy_bot/2.0.0/images/sha256-acdae1e09cfcbe971c91cfa42ad8825094cb95fa7e4ec10f42dde1b504f77ddd?context=explore)
