### ISSUE TITLE
How to include metadata annotations in decorated functions

### ISSUE THREAD

**Issue by unode** [attzonko/mmpy_bot#165]
In my fork I had [this change](https://github.com/unode/mmpy_bot/commit/156466efd86e450fac81d8dcea79a3806b48ef5d) that allows things such as `@respond_to('^userinfo +(.+)$', re.IGNORECASE, help="userinfo identifier", category="info", privileged=True)` these extra arguments would then be used in the custom help function (`default_reply`) to group commands under categories and to omit privileged commands from non-privileged users.
All of this always felt overly hacky so it was never up-streamed.

With the new release almost finished and the addition of `click` interfaces, any suggestions on how this could be achieved in 2.0 ?

Below some code to show how these were being used. The core of the change was exposing the decorator `kwargs` via `Matcher.attributes` (below `p.attributes`):

```python
def collect_commands(self, command_type, category_fmt_expr, cmd_fmt_expr, user):
    commands = {}
    for p, v in self._plugins.commands[command_type].items():
        if p.attributes.get("privileged") and user not in settings.PRIVILEGED_USERS:
            # Don't show privileged commands to non-privileged users
            continue
        else:
            category = p.attributes.get("category", "uncategorized")
            if category not in commands:
                commands[category] = []
            if p.attributes.get("help") is not None:
                commands[category].append((p.attributes.get("help"), v.__doc__))
            else:
                commands[category].append((p.regex.pattern, v.__doc__))

    collected = []
    # And displaying them alphabetically
    for category in sorted(commands):
        collected.append(category_fmt_expr.format(category))
        for help_cmd, description in sorted(commands[category]):
            collected.append(cmd_fmt_expr.format(help_cmd, description))

    return collected
```

Allowing a nice help:

```
Bad command `hi`,
these are the commands I understand:

* `admin`
    * `health` - Check the health of the bot by reporting active worker threads and if there are jobs scheduled
    * `shutdown` - Triggers a bot shutdown
* `info`
    * `userinfo identifier` - (...)
```

**Comment by jneeven** [comment]
We now have automatically generated help strings for every plugin, simply send `!help` anywhere. This function is registered on the base `Plugin` class, and `listen_to` has an argument `allowed_users`. It's probably a good idea to modify that help function to check whether the calling user is allowed to execute that function, and if not, omit that function from the help string.

I hope that's clear, I'm on my phone so can't easily link to the files... Feel free to make a PR if you want this implemented!

**Comment by unode** [comment]
Thanks, I'll have another read through and see how to go about it. Cheers!

**Comment by unode** [comment]
Ok, started making some progress in this and looking for some feedback.
I haven't found yet how to implement the following:

1. `category="info"`
2. `privileged=True`

For 1. it looks like the [click-option-group extension](https://click-option-group.readthedocs.io/en/stable/index.html) could help but it's focused on a documenting a single `@click.command()` instead of grouping multiple commands into one.
In the code in the initial comment, all commands are grouped and sorted alphanumerically by category.

As for 2. I found the existence of `hidden=True` that can be used to omit commands but have not found how to do it selectively for different users based on their status (`ADMIN`, `REGULAR`, ...)

Any suggestions on how to approach these?
