### ISSUE TITLE
`respond_to()` removed from mmpy_bot.bot module, how can I reply to message by my bot?

### ISSUE THREAD

**Issue by nautics889** [attzonko/mmpy_bot#169]
My goal for now is simply reply users on certain messages in direct chat. 
According to the [docs](https://mmpy-bot.readthedocs.io/en/latest/decorators.html) `respond_to(msg)` might be used as a decorator for such purposes and then properly configured bot starts replying to users after `bot.run()`. This method actually was in that module in older version, which i downloaded from PyPi. But how can i replace that in newest one? I couldn't find `respond_to(msg)` across whole library (so it'd been removed totatlly, not just relocated) and unfortunately didn't manage to figure out commit with such changes after a quick look through latest commits.

**Comment by jneeven** [comment]
We're still in the process of updating the docs before the 2.0 release (see #161 ), but for now you can have a look at [the example plugin](https://github.com/attzonko/mmpy_bot/blob/master/mmpy_bot/plugins/example.py#L14).

You now always use `listen_to`, but you can pass it `needs_mention=True` or `direct_only=True` if you need those criteria. In your specific case, the option you're looking for is `direct_only`. We'll add this to the migration guide!
