### ISSUE TITLE
bot stops responding after a while ver 1.3.9

### ISSUE THREAD

**Issue by SoundGoof** [attzonko/mmpy_bot#182]
**Describe the bug**
bot stops responding after a while
there is no error on stderr or stdout
it started happening after we upgraded mattermost to 5.33.0

is this the same bug that are reported against 2.0.0?

**How To Reproduce**
connect bot to mm-server, wait 10 min, stops responding almost all of the time

**Expected behavior**
reponds every time

**Operating Environment (please complete the following information):**
 - OS: debian 10
 - Python Version: 3.7.3
 - Mattermost Version: 5.33.0 and 5.33.1
 - mmpy_bot Version: 1.3.9
 
**Additional context**

**Comment by attzonko** [comment]
It sounds very similar to the issue you mention #171 

The issue was on the MM side and is supposed to be fixed in 5.33.2 which is being released shortly.

**Comment by attzonko** [comment]
I am assuming you confirmed it is the MM issue. If not and you still need help please re-open this issue.

**Comment by SoundGoof** [comment]
I can confirmed it is fixxed with mm ver 5.33.2
