### ISSUE TITLE
SSL_Verify is always True

### ISSUE THREAD

**Issue by saf6260** [attzonko/mmpy_bot#192]
**Describe the bug**
`SSL_VERIFY` flag in Settings fails to recognize `False` condition, causing complete shutdown of bot functionality

**How To Reproduce**
Either using a .env or direct setting adjustment, set `SSL_VERIFY=False` in Settings creation
```
settings=Settings(
    ...
    SSL_VERIFY=False
)
bot = Bot(
    settings=settings,
    plugins=[MyPlugin()],  # Add your own plugins here.
)
bot.run()
```

**Expected behavior**
SSL verification should not occur when the flag is set to False. However, current functionality seems to ignore the flag and produces a failure to verify issue with a self-signed cert

**Operating Environment (please complete the following information):**
 - OS: Linux and MacOS
 - Python Version: 3.9
 - Mattermost Version: latest (mattermost team docker image)
 - mmpy_bot Version: latest (2.0.0)
 
**Additional context**
If I manually change the value to false for the MM_driver, i can pass the SSL issues. However, the settings wrapper keeps the value true even if its set to false

**Comment by jneeven** [comment]
Strange! I have just tried to reproduce this in Python 3.8, but was unable to:
```python
from mmpy_bot import Settings

s = Settings(SSL_VERIFY=False)
print(s.SSL_VERIFY) # Prints "False"
```

I'll also try 3.9.

**Comment by saf6260** [comment]
Can do! It was a very strange issue to run into. I recently upgraded to the 2.0 release, so it may be something I'm doing, but for some reason I couldn't get the value to show `False` when I was working

**Comment by jneeven** [comment]
I've tried running your code above and have added a print statement in the `__init__` of `mattermostdriver.Driver`, and it prints `{'scheme': 'https', 'url': 'chat.com', 'port': 443, 'basepath': '/api/v4', 'verify': False, 'timeout': 30, 'request_timeout': None, 'login_id': None, 'password': None, 'token': 'token', 'mfa_token': None, 'auth': None, 'debug': False}`, as expected.

Which version of  `mattermostdriver` are you using? I'm on `7.2.0`

**Comment by jneeven** [comment]
What I think might be going on is that you set `SSL_VERIFY` to `False` in the code, but you have an environment variable that specifies otherwise?

From the `Settings` docstring:
```python
 """
    The order of priority in which settings are obtained is as follows:
    1. Environment variables
    2. Constructor arguments, if specified
    3. The default value set here.
    """

```

**Comment by saf6260** [comment]
Thanks overall for the fast feedback on this!

I do have an environment variable that I'm setting, however that value is also set to false on creation:
> cat .env
```
......
SSL_VERIFY=False
```
So no matter where this value is pulling from it should be false

I'm using version `7.1.0` so that may be part of it. I'm going to dig a bit more on my side to see where this conflict is occurring

**Comment by saf6260** [comment]
So I'm not sure how this happened, however here's a breakdown:

I was naming the `.env` key `SSL_VERIFY` and then sourcing the `.env` before each run of the bot. This was producing a `True` condition for the SSL verification. However, when I renamed the `SSL_VERIFY` in my `.env` to `MM_VERIFY`, then used:
```
settings = Settings(
    SSL_VERIFY=os.getenv("MM_VERIFY") == 'True' 
)
```
I get the proper value set, and the SSL verification is properly turned off

It appears there must have been some conflict in how this was being loaded, and that the only way it worked was for me to rename the `.env` key, which is odd. I'll try to recreate this a second time in a new repo to demonstrate

**Comment by saf6260** [comment]
Here's some test code to show what I mentioned above:
.env:
```
SSL_VERIFY=False
```

notifier.py
```
from mmpy_bot import Bot, Settings, ExamplePlugin
from dotenv import load_dotenv

load_dotenv()

settings = Settings(
    SSL_VERIFY=False,
)
print(settings)
```
Result: 
```
Settings(MATTERMOST_URL='chat.com', MATTERMOST_PORT=443, BOT_TOKEN='token', BOT_TEAM='team_name', SSL_VERIFY=True, WEBHOOK_HOST_ENABLED=False, WEBHOOK_HOST_URL='http://127.0.0.1', WEBHOOK_HOST_PORT=8579, DEBUG=False, IGNORE_USERS=[], SCHEDULER_PERIOD=1.0, SCHEME='https')
```

But with:
```
from mmpy_bot import Bot, Settings, ExamplePlugin
import os
from dotenv import load_dotenv

load_dotenv()

settings = Settings(
    SSL_VERIFY=os.getenv("MM_VERIFY") == 'True' ,
)
print(settings)
```

You get:
```
Settings(MATTERMOST_URL='chat.com', MATTERMOST_PORT=443, BOT_TOKEN='token', BOT_TEAM='team_name', SSL_VERIFY=False, WEBHOOK_HOST_ENABLED=False, WEBHOOK_HOST_URL='http://127.0.0.1', WEBHOOK_HOST_PORT=8579, DEBUG=False, IGNORE_USERS=[], SCHEDULER_PERIOD=1.0, SCHEME='https')
```

Which is the same as just renaming the value in the `.env`, which makes me believe that even with a `.env` the value must not be reading from the environment properly

**Comment by attzonko** [comment]
I reproduced the bug, and I think I found the root cause.

**Comment by attzonko** [comment]
in the `_set_field()` function we are doing `value = bool("False")` which is always going to be `True`

**Comment by attzonko** [comment]
@saf6260 Is it possible for you to verify the fix makes your issue go away?

**Comment by saf6260** [comment]
@attzonko it appears the env change there didn't register, unless I'm running something wrong:
requirements.txt
```py
git+git://github.com/attzonko/mmpy_bot@cfb88561872db8372213f2dbfafe51423bb777f9#egg=mmpy_bot
```
.env 
```
SSL_VERIFY=False
```

notifier.py
```py
from mmpy_bot import Bot, Settings, ExamplePlugin
import os
from dotenv import load_dotenv

load_dotenv()

print(os.getenv("SSL_VERIFY"))

# settings = Settings(
#     BOT_TOKEN="1234",
# )
bot = Bot()
print(bot.settings)
```
Prints -> 
```py
False
Settings(MATTERMOST_URL='chat.com', MATTERMOST_PORT=443, BOT_TOKEN='token', BOT_TEAM='team_name', SSL_VERIFY=True, WEBHOOK_HOST_ENABLED=False, WEBHOOK_HOST_URL='http://127.0.0.1', WEBHOOK_HOST_PORT=8579, DEBUG=False, IGNORE_USERS=[], SCHEDULER_PERIOD=1.0, SCHEME='https')
```

**Comment by attzonko** [comment]
You are welcome. @jneeven deserves the credit for the big refactor for 2.x, I am just happy to see the idea live on and the code taking advantage of newer technologies like asynchio.  I am sure there will be some minor clean-up like this, but overall I think the move to 2.x is a good one, bringing the bot code closer to the Mattermost API, by taking advantage of the exiting MM driver. Not to mention adding the ability to support webhooks with the bot itself.

**Comment by saf6260** [comment]
I think my pull of the PR was wrong -> Running your change in the repo itself fixes the issue. Thanks again for the quick fix!
