### ISSUE TITLE
Installation via tar file fails due to missing requirements.txt

### ISSUE THREAD

**Issue by ttuffin** [attzonko/mmpy_bot#202]
**Describe the bug**
When trying to install 2.0.1 via the tar file hosted at PyPi it fails with: `FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'`

We need to add the file and fix this release.

**How To Reproduce**
1. Download [mmpy_bot-2.0.1.tar.gz](https://files.pythonhosted.org/packages/cc/b4/c695a37ea5be52715cb06af3a4993c1524ccbb775e31dda707d9c38eae87/mmpy_bot-2.0.1.tar.gz) 
2. Try to install using pip: `# mmpy_bot-2.0.1.tar.gz`

**Expected behavior**
mmpy_bot installs correctly from the tar file

**Operating Environment (please complete the following information):**
 - mmpy_bot Version: 2.0.1

**Comment by ttuffin** [comment]
@attzonko I think only you can fix the PyPi releases right?

**Comment by attzonko** [comment]
Thanks for catching this. I'll have to make a 2.02, I don't think PyPi allows overwriting existing files.

**Comment by attzonko** [comment]
Version 2.0.2 released to Pypi with missing files for Tar install included.

**Comment by jneeven** [comment]
> I think only you can fix the PyPi releases right?

We can easily automate this with https://github.com/pypa/gh-action-pypi-publish if desired. I have some experience with it from other Python packages I've worked on and it's very straightforward. We'd just need to add a workflow file and set a pypi token as a secret for this repo

**Comment by attzonko** [comment]
> > I think only you can fix the PyPi releases right?
> 
> We can easily automate this with https://github.com/pypa/gh-action-pypi-publish if desired. I have some experience with it from other Python packages I've worked on and it's very straightforward. We'd just need to add a workflow file and set a pypi token as a secret for this repo

I am in favor of automating it 👍🏼
