### ISSUE TITLE
Automate release to Pypi

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#206]
Opening this issue to track the discussion about automating the release to pypi.org from #202 where @jneeven mentioned
> We can easily automate this with https://github.com/pypa/gh-action-pypi-publish if desired. I have some experience with it from > other Python packages I've worked on and it's very straightforward. We'd just need to add a workflow file and set a pypi token as > a secret for this repo

**Comment by attzonko** [comment]
I added a secret to this repository: PYPI_API_TOKEN

**Comment by jneeven** [comment]
Awesome, I'll make a PR once I have time

**Comment by attzonko** [comment]
Cool, I assume the action will be triggered on a new TAG being pushed. How can we enforce for the version string to get updated accordingly? Can we automate making a GitHub release at the same time?

**Comment by jneeven** [comment]
> Cool, I assume the action will be triggered on a new TAG being pushed. How can we enforce for the version string to get updated accordingly? Can we automate making a GitHub release at the same time?

With the setup I use normally, you manually make a github release, which will trigger the action to create & publish the wheels to pypi. We'll still need to manually update the version string; it *should* be possible to also have the action write that to some file that we then read it from but we'd need to make a bot account with permission to commit etc so I'm not sure that's worth the complexity...

**Comment by attzonko** [comment]
So the proposed release flow would be something like:
1. Update version number (`mmpy_bot/__init__.py` & `setup.py`) make commit and tag
2. Build the release files ( `mmpy_bot-<ver>-py3-none-any.whl` & `mmpy_bot-<ver>.tar.gz`)
2. Push commit and tag to GitHub
3. Make a GitHub Release uploading the built release files
4. Action is triggered and publishes release files to PyPi

Is that how you see it too?

**Comment by jneeven** [comment]
Step 2 is done automatically by the action; no need to build anything. Other than that this sounds about right :+1:

**Comment by attzonko** [comment]
I am a bit confused, sorry. So we would make a release without building first and the action would be triggered and it would build and add the `*.whl` and `*.tag.gz` to the new release and publish to Pypi? What if the build fails?

**Comment by jneeven** [comment]
>  What if the build fails?

Then it never reaches the publishing stage 😅 Which unfortunately does mean you'll have to make *another* release with an incremented version to re-trigger it

**Comment by jneeven** [comment]
I'll just make that PR and you'll see soon enough how it works. If it doesn't meet our needs we can always tweak or remove it :+1:

**Comment by attzonko** [comment]
I was thinking we can automate [creating the release](https://github.com/marketplace/actions/automatic-releases) as well. That way if the build fails, a Github release will not be generated. 

Also, couldn't we [manually run](https://github.com/marketplace/actions/automatic-releases) the workflow that builds and generates the release and publishes to Pypi?

**Comment by jneeven** [comment]
Yes absolutely, I do have a setup like that elsewhere but I think it doesn't create any GitHub releases. Looks like there are plenty of possibilities though so we can definitely get it working somehow
