### ISSUE TITLE
Getting 1.3.9 when wanting latest 2.0.2 from pip

### ISSUE THREAD

**Issue by Beanzilla** [attzonko/mmpy_bot#221]
**Describe the bug**
I look at the wiki/docs (which I assume is for 2.0.2), I follow along with `pip install mmpy_bot`, but it installs 1.3.9 rather than 2.0.2.

**How To Reproduce**
For me:

1. I create a new python virtual environment `python3 -m venv env`,
2. Activate the environment `. env/bin/activate`,
3. Then attempt to install latest mmpy_bot `pip3 install mmpy_bot`,
4. Result is 1.3.9 instead of 2.0.2. (I've even tried requesting 2.0.2 and according to my python it only sees 1.3.9 as latest)

**Expected behavior**
I expect 2.0.2 mmpy_bot to be installed, or at least a newer version besides 1.3.9.

**Operating Environment (please complete the following information):**
 - OS: Linux
 - Python Version: 3.6.9
 - Mattermost Version: 5.31.0
 - mmpy_bot Version: (I'm trying to rewrite/refactor my code from 1.3.9 to 2.0.2)
 
**Additional context**
And 1.3.9 of course doesn't do things the way 2.0.2 shows... thus I wish to report this. (No big rush, just would like to get the latest to use it instead)

Can I git clone this repo and "build" or "install" the mmpy_bot into the python virtual envrionment?

 Or maybe have my code use the mmpy_bot from the repo? (Instead of the one installed via pip)

**Comment by attzonko** [comment]
First things first, you can always install from the repo...

We'll have to look into why you are getting the old version....

**Comment by Beanzilla** [comment]
Ah, ok, I will look into installing from repo then.

Thank you for this cool project.

**Comment by attzonko** [comment]
I think looking at your info closer it is because Python 3.6.9, technically 2.x requires: Python >=3.8

**Comment by Beanzilla** [comment]
> I think looking at your info closer it is because Python 3.6.9, technically 2.x requires: Python >=3.8

Yeah, might be also why I am having an issue with an `ImportError: cannot import name 'cached_property'`.

My poor old python is not new enough. :)

**Comment by attzonko** [comment]
I updated the README to have a warning about this in the Install section.

**Comment by Beanzilla** [comment]
Hey yeah python3.8 grabs 2.0.2 :smile:

Thank you for the support, and the bot.
