### ISSUE TITLE
version.txt not available after installation

### ISSUE THREAD

**Issue by unode** [attzonko/mmpy_bot#230]
This is preventing import after install:

https://github.com/attzonko/mmpy_bot/blob/bd0eeab382dfbb3a74576f98257de7fb89f187c9/mmpy_bot/__init__.py#L15

I tried adding `include_package_data=True` to `setup.py` as described in https://python-packaging.readthedocs.io/en/latest/non-code-files.html without success.

In addition, given `mmpy_bot` installs to `site-packages/mmpy_bot`, `version.txt` would have to be installed to `site-packages/version.txt` which may cause troubles if other packages do the same.

**Comment by unode** [comment]
Tagging @jneeven as this seems to have been introduced in https://github.com/attzonko/mmpy_bot/commit/47fca9301b53941e9e0b96169dcc97f57b850f00 as part of #208

**Comment by jneeven** [comment]
I see, we can probably just move it one folder down 👍🏼

**Comment by unode** [comment]
We were also missing a few lines in `setup.py` to ensure the file is installed from a wheel.
