### ISSUE TITLE
Posting channel posts without the need for listening for user input

### ISSUE THREAD

**Issue by JerrickLiu** [attzonko/mmpy_bot#240]
I was wondering for the matter most bot that you guys created if there is a way to post a message after some form of logic has passed rather than some listening for messages? For example, I wanted to create a plugin such that when a new video was uploaded to our google drive the bot would automatically post a link to it in one of our channels. Does your bot support that functionality?

**Comment by jneeven** [comment]
As answered on Discord: I'm not sure about Google Drive specifically, but anything that can automatically call a webhook would work: https://mmpy-bot.readthedocs.io/en/latest/plugins.html#webhook-listener

**Comment by attzonko** [comment]
For something like this, I would suggest just use a webhook natively in Mattermost. No need for a bot.
Take a look at this blog post: https://mattermost.com/blog/mattermost-integrations-incoming-webhooks/
