### ISSUE TITLE
Fix Mattermost capitalization in project description

### ISSUE THREAD

**Issue by bbodenmiller** [attzonko/mmpy_bot#243]
`MatterMost` -> `Mattermost`

**Comment by attzonko** [comment]
Can you point me to a specific page/doc/etc.? I looked and can't find the case you are referring to.

Thanks!

**Comment by bbodenmiller** [comment]
@attzonko 

![image](https://user-images.githubusercontent.com/1192780/126572095-24c9d2d2-d542-431a-b532-57b40f0722d9.png)
