### ISSUE TITLE
open dialog error with trigger_id by button

### ISSUE THREAD

**Issue by twofrogs** [attzonko/mmpy_bot#245]
**Describe the bug**

All are working fine in example codes. Firstly, I have to say thank you for this good module. 

In example codes, I couldn't find codes to open dialog. 
So, I wrote simple dialog (json format) and tried to send it to server using mattermostdriver api.
- `trigger_id` come from **button click interaction**. 

```
@listen_webhook("email")
async def action_email(self, event: WebHookEvent):
    options = {
        "trigger_id": event.trigger_id,
        "url": "http://xxx.xxx.xxx.xxx/hooks/submission",
        "dialog": {
            "callback_id": "email-edit",
            "title": 'dialog title',
            "elements": [
                {
                    "display_name": "Email",
                    "name": "email",
                    "type": "text",
                    "subtype": "email",
                    "placeholder": "placeholder@example.com"
                }
            ],
            "submit_label": 'Set',
            "notify_on_cancel": False
        }
    }

    result = self.driver.integration_actions.open_dialog(options)
    logger.info(f"Sent response for action [{event.webhook_id}]: {result}")
```

result also was fine : {'status': 'OK'}
But, I couldn't see any dialog popup on mattermost client.  Server side error log was followings:
 

```
{
    "level":"debug",
    "ts":1627368085.8932252,
    "caller":"mlog/log.go:230",
    "msg":"Action integration error.",
    "path":"/api/v4/posts/fdfsdf3yjnfsfd6fa7gfdg/actions/notification",
    "request_id":"rterte9hpf65e7xif3453435reto",
    "ip_addr":"xxx.xxx.xxx.xxx",
    "user_id":"s3a7iin242342sdfdsdo7oqjm6y",
    "method":"POST",
    "err_where":"DoPostActionWithCookie",
    "http_code":400,
    "err_details":"err=EOF"
}
```

On the other hand, I tried to send the same json data with `trigger_id` by slash command (Not using mmpy_bot module)
It worked well so, json data itself is perfect. 

I found similar error report [here](https://forum.mattermost.org/t/interactive-dialog-cannot-call-from-interactive-message-button/11850/2)

Any one succeeded to open dialog with latest mmpy_bot ??
Could you guide me any missing in my code ?

**Operating Environment (please complete the following information):**
 - OS: [Linux]
 - Python Version: [3.9]
 - Mattermost Version: [5.37.0]
 - mmpy_bot Version: [2.0.2]

**Comment by twofrogs** [comment]
Self solution :)

Before fire open_dialog, need to call respond_to_web first.

**Comment by Class-D-personnel** [comment]
Hello there.
It would be old codes, but I wanna get some help about dialog form.
Below here, there are some mmpy code of old version(exactly called as webhook_example.py), and I'm finding how to make interactive dialog by chatbot in recent version of mmpy-bot.
In below case, the error ocurred by that there are no "integration_actions" or "open_dialog" in the given library.
What code can displace "integration_actions" so that interactive dialog is able to works?



    @listen_webhook("dialog")
    def dialog_listener(self, event: WebHookEvent):
        if isinstance(event, ActionEvent):
            self.driver.respond_to_web(
                event,
                {
                    "update": {"message": event.context["text"], "props": {}},
                    "ephemeral_text": "dialog",
                },
            )
            options = {
                "trigger_id" : event.trigger_id,
                "url": f"{self.webhook_host_url}:{self.webhook_host_port}/hooks/dialog_submit",
                "dialog" : {
                    "callback_id": "email-edit",
                    "title": 'dialog title',
                    "elements": [
                    {
                        "display_name": "Email",
                        "name": "email",
                        "type": "text",
                        "subtype": "email",
                        "placeholder": "placeholder@example.com"
                    }
                    ],
                    "notify_on_cancel": False
                }
            }
            self.driver.integration_actions.open_dialog(options)  

        else:
            pass
