### ISSUE TITLE
Loading multiple plugins which listen to the same regex

### ISSUE THREAD

**Issue by seLain** [attzonko/mmpy_bot#25]
This is a proposal for supporting **multiple plugins listening to the same regex**. Previous discussion can be found in https://github.com/attzonko/mmpy_bot/pull/24#issuecomment-404410797 . 

This is not an emergent proposal. **Further discussion on actual needs, implementation details, and trade-off are welcomed.**

#### Issue 
If there are two plugin functions listening to the same regexp pattern, only the latest loaded function will be kept in ``PluginsManager``. Details can be found in ``Bot.listen_to()``. 

``Bot.listen()`` decorator function will keep only one function for one regex pattern.

```python
def listen_to(regexp, flags=0):
    def wrapper(func):
        r = re.compile(regexp, flags | re.DEBUG)
        PluginsManager.commands['listen_to'][r] = func
        logger.info(
            'registered listen_to plugin "%s" to "%s"', func.__name__, regexp)
        return func

    return wrapper
```
In some cases, if we need two unrelated plugins being used which listen to the same regex, this can be an issue.

#### Current solution
A workaround solution can be made by delegation :
```python
@listen_to('hello$')
def hello_dispatcher(message):
    hello_send(message)
    hello_louder(message)

def hello_send(message):
    message.send('hello channel!')

def hello_louder(message):
    message.send('HELLO CHANNEL!!!')
```
If you need ``hello_send`` and ``hello_louder`` to execute concurrently, simply executing them in different subprocesses.

#### Solution to be discussed
Enabling ``PluginsManager`` to keep multiple plugins listening to the same regex provides a direct solution to this issue. In this solution, we can have : 
```python
@listen_to('hello$')
def hello_send(message):
    message.send('hello channel!')

@listen_to('hello$')
def hello_louder(message):
    message.send('HELLO CHANNEL!!!')
```
And both ``hello_send`` and ``hello_louder`` will be loaded.

#### Pros and Cons
Pros
- Developer can add plugins freely without an additional dispatcher to delegate message.  
- The proposed solution is compatible with the delegation solution.

Cons
- If there are lots of plugin functions introduced, the developer has to find way managing multiple plugins listening to the same regex. While the delegation solution enforces developer to manage all plugins by the dispatcher.

**Comment by attzonko** [comment]
I am in agreement with this proposed solution. I want to understand the con you listed. what do you mean by developer has to manage multiple plugins listening to the same regex? If we have two plugins that end up having the same regular expression in their listen_to(), the PluginsManager would just handle that and would trigger both plugins. What does the developer need to manage himself? Just to know that their are multiple plugins which would trigger? If that is the case, doesn't the summary in the logs give a good place to see/get that information? 

In general, do you think this is actually needed at this point? The workaround you suggest works, perhaps we should error on the side of [KISS ](https://en.wikipedia.org/wiki/KISS_principle) and wait until there is an overwhelming request from the community to add this capability?

**Comment by seLain** [comment]
Yes, the logs provide adequate info to trace plugins triggered. In my case, plugins for a bot are contributed by various group members without consistent document maintained. We use the workaround solution to make sure contributors knowing all plugins listening to the same regex before actually adding another. In multiple plugins solution, we might need to manage these plugins in the same module for that.

Current solution by delegation work for me :)  
I agree we should wait for actual needs from the community.
