### ISSUE TITLE
basepath for driver not supported

### ISSUE THREAD

**Issue by Leanny** [attzonko/mmpy_bot#261]
**Describe the bug**
Since 2.0.0 the bot uses `MATTERMOST_URL` for the base url and `MATTERMOST_PORT` for the port, as well as assuming that `/api/v4` is the api basepath for the driver. While in 1.x it was possible to simply give `BOT_URL` something like `localhost:9090/mattermost/api/v4` as API url, this is no longer possible with the current version of the bot due to missing `basepath` argument when passing arguments to `Driver`.

**Expected behavior**
Add `basepath` as a setting and pass it to `Driver` as well

**Comment by jneeven** [comment]
We're using `mattermost-driver` [pretty much as-is](https://github.com/attzonko/mmpy_bot/blob/main/mmpy_bot/bot.py#L38-L48), so if specifying url `localhost/mattermost/api/v4` and port `9000` doesn't work, that sounds like an issue for https://github.com/Vaelor/python-mattermost-driver. Could you open one there if necessary?

**Comment by Leanny** [comment]
The solution is to simply pass `basepath` as well, as the driver already supports this feature:

```
        self.driver = Driver(
            {
                "url": self.settings.MATTERMOST_URL,
                "port": self.settings.MATTERMOST_PORT,
                "basepath": self.settings.MATTERMOST_API_PATH,
                "token": self.settings.BOT_TOKEN,
                "scheme": self.settings.SCHEME,
                "verify": self.settings.SSL_VERIFY,
                "keepalive": True,
                "connect_kw_args": {"ping_interval": None},
            }
        )
```

If you pass `{"url": "localhost", "port": 9000, "basepath": "/mattermost/api/v4", [...]}` then it will behave correctly.

**Comment by jneeven** [comment]
Ah great! In that case, feel free to make a PR here to support this 👌🏼
