### ISSUE TITLE
IGNORE_NOTIFIES parameter not working

### ISSUE THREAD

**Issue by ralgozino** [attzonko/mmpy_bot#27]
Hello!

According to the [docs](http://mmpy-bot.readthedocs.io/en/latest/settings.html) an `IGNORE_NOTIFIES` parameter can be defined in the settings wich stablishes wich users will the bot ignore. In our case, this is not working.

With the [original mattermost bot](https://github.com/LPgenerator/mattermost_bot) module I could override this behaviour by using `message.get_username()`, but this doesn't seem to be working with `mmpy_bot`, at least when the message comes from a post made by an "Incoming Webhook" (has the "bot" flag next to the username).

Let me know if you need more information!

Cheers!

**Comment by seLain** [comment]
Hi @ralgozino , are you trying to ignore **messages from specific users** by ``IGNORE_NOTIFIES`` ? Please correct me if I am wrong.

It seems the original intention of ``IGNORE_NOTIFIES`` is to ignore broadcasting messages. Although it can also be used to ignore **messages mentioning specific users**.

For example, say we have users **Amy** and **Betty** online ( and a bot of course ), and the  ``IGNORE_NOTIFIES`` is set to ``['@channel', '@all', '@Betty']``.

These messages will be ignored : 
```text
Amy says: @all hello
Amy says: @Betty hello
```
While these will **not** be ignored : 
```text
Amy says: hello
Betty says: hello
```

**Comment by attzonko** [comment]
I agree @seLain the IGNORE_NOTIFIES indicates which broadcast messages the bot will ignore. 

Are you trying to ignore other bots? Or what exactly are you trying to do?

**Comment by ralgozino** [comment]
ohhhh.. right! My bad! I was using the parameter to (try) to ignore specific users, like other bots. I Missunderstood.

The second part of my first post is still valid though. I was using `message.get_username() in ["Bot1", "Bot2"]` to ignore other bots with the original `mattermost_bot`, but is seems that is not working with `mmpy_bot` now. I'll try to debug it better.

I think a parameter to ignore certain users (like bots) will be useful. What do you think??

**Comment by attzonko** [comment]
I think it should work the way you are thinking. Do you mind throwing a print before your conditional to see exactly what `message.get_username()` is returning to you?

As far as the parameter idea, are you thinking along the lines of a setting parameter like IGNORE_USERS = ["bot1","bot2"]?

I don't see any obvious reason not to add something like that 
@seLain do you?

**Comment by seLain** [comment]
Totally agree. It's useful. I think I can add the parameter and corresponding behavior later :smiley: .

**Comment by seLain** [comment]
Made it in PR #29 . Check it out for details. :laughing:

**Comment by attzonko** [comment]
The PR #29 is merged now. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ralgozino** [comment]
@seLain Thank you! When will the merge be released so I can update using `pip`?

@attzonko I made some more testing, and `message.get_usernane()` of a bot's message, returns the owner of the webhook; but using `message._get_sender_name()` returns de bot name. I don't know if this is the desired behaviour; may be `_get_sender_name()` should be exposed?

**Comment by attzonko** [comment]
@ralgozino I'll try and make a pypi release this week. 

Regarding the get_username. It is not a V3 vs V4 API version, both API versions work the same.

I did confirm that there was a change in the bot code that introduced this change in behavior. With the old code we used to always just return the _get_sender_name() if there was a request for get_username()
``` 
   def get_user_info(self, key, user_id=None):
        if key == 'username':
            sender_name = self._get_sender_name()
            if sender_name:
                return sender_name

        user_id = user_id or self._body['data']['post']['user_id']
        if not Message.users or user_id not in Message.users:
            Message.users = self._client.get_users()
        return Message.users[user_id].get(key)

    def get_username(self, user_id=None):
        return self.get_user_info('username', user_id)
```
the new code below does not have that special case for username this was a change I introduced inadvertently when I cleaned up the way user info is acquired. I think this needs to be correctedI opened a new issue #30 for tracking that.
```
def get_user_info(self, key, user_id=None):
        user_id = user_id or self._body['data']['post']['user_id']
        user_info = self._client.api.get_user_info(user_id)
        return user_info[key]

    def get_username(self, user_id=None):
        return self.get_user_info('username', user_id)
```
