### ISSUE TITLE
Double log output on console if no log file is given

### ISSUE THREAD

**Issue by GerdWiegand** [attzonko/mmpy_bot#271]
**Describe the bug**
If no log file is given the console output is duplicated.

**How To Reproduce**
Leave LOG_FILE unset. Start the bot.

**Expected behavior**
Only one line per log message should be seen

**Operating Environment (please complete the following information):**
 - OS: Linux
 - Python Version: 3.8
 - Mattermost Version: all
 - mmpy_bot Version: 2.0.3

**Additional context**
A patch for this behaviour is added as attachment.
[0001-Fix-double-console-log-if-no-log-file-is-given.patch.gz](https://github.com/attzonko/mmpy_bot/files/7443117/0001-Fix-double-console-log-if-no-log-file-is-given.patch.gz)

**Comment by attzonko** [comment]
Thanks @ttuffin for implementing the fix.
