### ISSUE TITLE
Login failed in version 6.3.0

### ISSUE THREAD

**Issue by tgly307** [attzonko/mmpy_bot#283]
**Describe the bug**
Update mm_server from 6.2.0 to 6.3.0, the bot login failed.
The log is:
```
[01/16/2022 02:44:18][mattermostdriver.websocket][WARNING] Failed to establish websocket connection: code = 1006 (connection closed abnormally [internal]), no reason
[2022-01-16 02:44:18,257][mattermostdriver.websocket][WARNING] Failed to establish websocket connection: code = 1006 (connection closed abnormally [internal]), no reason
```
**How To Reproduce**
Give us simple steps to reproduce the behavior:
Update mm_server from 6.2.0 to 6.3.0
start bot
**Expected behavior**
Log in normally
**Operating Environment (please complete the following information):**
 - OS: [Linux]
 - Python Version: [3.8]
 - Mattermost Version: [6.3.0]
 - mmpy_bot Version: [2.0.2]

**Additional context**
Add any other context about the problem here [e.g. Settings for your bot, API Version]

**Comment by tgly307** [comment]
Thank you for your reply. I didn't notice this PR before. Will this change cause that the servers before 6.3.0 cannot be logged in？

**Comment by ttuffin** [comment]
I posted this to the mattermost-driver issue as well:
> I have not had any issues when testing this change against MM 5.26.0, which also uses API v4. It may break for API v3, but since it has been deprecated since 2018 I don't think it's a blocker.

Further, I don't see any particular need for the authentication data to be encoded, except that it consumes slightly less memory (a negligable difference). Prior to MM-40485, sending non-encoded data works fine as well, but now that they have changed the decoder it seems to no longer accept UTF encoded data.
