### ISSUE TITLE
Bot won't match in middle of text, re.match() vs re.search()

### ISSUE THREAD

**Issue by benbart** [attzonko/mmpy_bot#289]
I've recently updated my bot to 2.0.2 and noticed a change in behavior that broke several functions.

Given the following plugin:
```python
class ThisPlugin(Plugin):
    @listen_to(r'foo')
    async def foo(self, message: Message):
        self.driver.reply_to(message, 'foo found')

    @listen_to(r'.*bar')
    async def bar(self, message: Message):
        self.driver.reply_to(message, 'bar found')
```

If a mattermost user enters the text:
> Some text foo. Some text bar. Some more text baz.

I would expect the bot to invoke both `foo()` and `bar()`, but will only respond with "bar found". So I dug around. I see that [mmpy_bot uses re.match()](https://github.com/attzonko/mmpy_bot/blob/main/mmpy_bot/event_handler.py#L91), which only matches from the beginning of a string,  rather than re.search(). mmpy_bot 1.x used re.search(). 

I'm not completely expert at regex, but preceding all my patterns with a `.*` seems hacky. Is it possible to have a mode where re.search() is used instead? Or refactor so the matching can be more easily addressed in a subclass? Or I'd be happy to make a PR to change to search() if the devs aren't opposed to that change.

**Comment by ttuffin** [comment]
Thanks for reporting this. I don't see any issue switching to `re.search`, works fine in my tests. @attzonko, do you have any thoughts on this?

**Comment by benbart** [comment]
I meant to include this in my original post, but `re.match()` is faster than `re.search()`. For my use case, that's not an issue at all. I thought the change might have been to address speed needs for some users/.

**Comment by attzonko** [comment]
Since this was how it worked before the 2.x re-write I am fine with reverting it to the old behavior, despite the small reduction in performance.
