### ISSUE TITLE
Accepting command with and without arguments

### ISSUE THREAD

**Issue by FrankvdHorst** [attzonko/mmpy_bot#301]
Hello everyone,

sorry if this is a stupid question, but how can I accept a command to react with or without an argument?

For example: I have taken from the example plugin the !info trigger. Now I would like to let the bot reply to both the following:

!info
!info test message

I know that in the code you can specify the arguments variable, and this works fine, but when I do that the bot isn't reacting anymore to an empty !info trigger. It simply expects something behind it (an argument) and doesn't want to work without it.

Right now I have the following code:

    # Info trigger WITH argument:
    @listen_to("^!info (.*)$", re.IGNORECASE)
    async def info(self, message: Message, argument: str):
        """Responds with the user info of the requesting user."""
        user_email = self.driver.get_user_info(message.user_id)["email"]
        
        if not argument:
            self.driver.reply_to(message, "No argument supplied!")
            return
        
        reply = (
            f"TEAM-ID: {message.team_id}\nUSERNAME: {message.sender_name}\n"
            f"EMAIL: {user_email}\nUSER-ID: {message.user_id}\n"
            f"IS-DIRECT: {message.is_direct_message}\nMENTIONS: {message.mentions}\n"
            f"MESSAGE: {message.text + ' ' + argument}"
        )
        self.driver.reply_to(message, reply)

But as said this doesn't reply when you only do a !info without any arguments!

Can someone please point me in the right direction?

Thanks for your help!

**Comment by FrankvdHorst** [comment]
ok, was a bit to quick and figured it out :-)

You just have to make 2 command with different def names:

**With** an argument:
`
@listen_to("^!info (.*)$", re.IGNORECASE)
async def info_with(self, message: Message, argument: str):
`

**Without** and argument:
`
@listen_to("^!info$")
async def info_without(self, message: Message):
`

**Comment by attzonko** [comment]
Yup you got it.
