### ISSUE TITLE
Issues with mmpy_bot, click and spaces

### ISSUE THREAD

**Issue by sw-dbrown** [attzonko/mmpy_bot#338]
**Describe the bug**

When specifying options with the click-based interface, spaces seem to count as valid option values. This means that the bot will return an error message or have the wrong behavior (e.g. when positional arguments are used). 

**How To Reproduce**
Create a bot with the following listener:

```
    @listen_to(
        "dummy",
    )
    @click.command()
    @click.option(
        "-a",
        "--cmda",
        type=str,
        required=True,
    )
    @click.option(
        "-b",
        "--cmdb",
        type=str,
        required=True,
    )
    def dummy(self, message, cmda: str, cmdb: str) -> None:
        self.driver.reply_to(message, f"cmda: {repr(cmda)}\ncmdb: {repr(cmdb)}")
```
Send the message `dummy -a foo -b foo` and observe that the parameters were parsed correctly:

```
cmda: 'foo'
cmdb: 'foo'
```

Now send the message `dummy -a  foo -b foo` (not the second space after `-a`) instead and observe the following error message:

```
Got unexpected extra argument (foo)

Usage: dummy [OPTIONS]

Options:
  -a, --cmda TEXT  [required]
  -b, --cmdb TEXT  [required]
  --help           Show this message and exit.
```

**Expected behavior**

Since it is quite easy to add extra spaces by accident, it would be great if this case could be handled somehow. The most useful behavior would probably be to perform a `strip()` operation somewhere but I am not familiar enough with the code base to make the change myself. I'd be willing to take a look into it though, if I can get some pointers.

Thanks for your time!

**Operating Environment (please complete the following information):**
 - mmpy_bot Version: mmpy_bot-2.1.0
 - mattermostdriver Version: mattermostdriver-7.3.2
 - Mattermost Server Version: 7.1.2
 - Python Version: 3.9.2
 - OS: Linux

**Additional context**

-

**Comment by unode** [comment]
Thanks for the bug report. This should now be fixed.

**Comment by sw-dbrown** [comment]
Thanks for the very fast response. I can confirm that the issue is fixed!

> Thanks for the bug report. This should now be fixed.
