### ISSUE TITLE
How to deploy the bot on EC2 or Google Cloud

### ISSUE THREAD

**Issue by maddyonline** [attzonko/mmpy_bot#346]
I am curious how to deploy the bot to one of the cloud platforms. I understand that one can just create a python binary. But does one need to expose any particular PORT for incoming requests/outgoing requests?

In particular, it is not clear to me if the bot itself is a webserver and some kind of gunicorn like setup is required to set it up in prod instances.

**Comment by attzonko** [comment]
The bot communicates with the Mattermost Server on the port defined in settings. The communication goes over HTTP/HTTPS as well as WebSocket connection. Further, the bot does have the ability to optionally run an internal webserver to be used for Incoming Webhooks when dealing with more advanced Mattermost features such as dialogs, buttons, etc. 

To deploy the bot in a cloud platform, all you would need is to be able to install the bot,  for example via the `pip install` command. You can easily deploy it as a Docker container image. Take a look at the Dockerfiles at the top of the repo. That is how we deploy it in GitHub Actions for testing.

**Comment by attzonko** [comment]
@maddyonline Please feel free to re-open if you have any other questions.
