### ISSUE TITLE
Is it time to remove API V3 completely?

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#40]
Just wanted to get some opinions. I think we should completely remove support for API V3. 

Any strong objections why we should not do it?

**Comment by seLain** [comment]
I am actually using APIv4 only ... and we have MM 5 now... it's time :p

Btw, will there be APIv5 ? I didn't see any info regarding APIv5.

**Comment by attzonko** [comment]
I doubt it. I have not seen any info on it.
