### ISSUE TITLE
[Question] Register plugins at runtime

### ISSUE THREAD

**Issue by joalif** [attzonko/mmpy_bot#414]
Hello,

In my team, we use mmpy_bot to integrate mattermost with our ticketing system.
For our use case, I'd like to be able to register some plugins at runtime, after
the bot is created as shown below:  
```
settings = ...
plugins = [Pugin1(), Plugin2()]
enable_logging = False
bot =  Bot(settings, plugins, enable_logging)
bot.run()
# do some stuff
# register some extra plugins here
```
Is this possible? And if possible what's the proper way to do it?

Thanks,
Jo

**Comment by unode** [comment]
Hi Jo,

It may be possible but this isn't a supported use-case. The reason being that certain plugin initiation routines are executed when the bot launches.

To achieve some form of dynamic editing, you could always implement a system that populates the list of plugins from a text file or database, but a bot restart would still be required.

Cheers,
Renato
