### ISSUE TITLE
Scheduled responses to channel instead of reply

### ISSUE THREAD

**Issue by EM-Tom** [attzonko/mmpy_bot#418]
Hey, first off love the plugin. 

I'm currently looking to use the scheduler functionality to post a regular message into a whole channel. 
So far I have only managed to get the bot to reply to my initiation message on the schedule, this I can see is by design. 

Is it possible to respond to the entire channel (IE a new message in the channel) instead of direct ?

**Comment by unode** [comment]
The attribute passed to `.do()` needs to be a function.
In your code you are passing the result of calling the `create_post()` function.

**Comment by EM-Tom** [comment]
Thanks again, so I can't use the  ``self.driver.create_post`` as an output of the scheduler?  My want is a repeating messaged based on a schedule in a channel post, not reply.

**Comment by unode** [comment]
Please see the example I mentioned above. It answers your question. The point is, you don't call the function but instead pass the function to be called along with the arguments. Pay attention to the position of the parenthesis in the example and your code.
