### ISSUE TITLE
How to send files to bot directly for some postpone processing?

### ISSUE THREAD

**Issue by muirdok** [attzonko/mmpy_bot#424]
Hi!
I'd like to say thank you for this awesome project. It's really helpful and easy to use.
My question here - Is it possible to send file (.zip) as user for some processing directly to bot? 
E.g. user send file to bot in direct message and it uses smth like  `@listen_to("test.zip", re.ISFILE)` or `message.files` to get file or url to files what was attached for message.

Many thanks!

**Comment by unode** [comment]
Attachments is not something that is listened on. Any message can have an attachment.
You inside of the trigger function you need to check if the message includes any attached file.

See the example code below:

```python
try:
    files = message.body["data"]["post"]["metadata"].get("files", ())
except KeyError:
    logger.exception("Unexpected reply from Mattermost")
    self.driver.reply_to(
        message,
        "An unexpected error occurred while trying to obtain the attached file. "
        "The error has been logged.",
    )
    return
else:
    if len(files) != 1:
        self.driver.reply_to(
            message,
            "Too few or too many files attached. "
            "Please attach exactly one file.",
        )
        return

reply = self.driver.files.get_file(files[0]["id"])
file_contents = reply.content
```

**Comment by unode** [comment]
@muirdok If the above answered your question, feel free to close this issue.

**Comment by muirdok** [comment]
Thanks! I'll try it.
