### ISSUE TITLE
Fix "similar-code" issue in mmpy_bot/mattermost.py

### ISSUE THREAD

**Issue by attzonko** [attzonko/mmpy_bot#44]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/attzonko/mmpy_bot/mmpy_bot/mattermost.py#issue_5b5aee0ecaca12000100004f

**Comment by attzonko** [comment]
@seLain Do we really need the 'delete' method? Looks identical to the 'post' method.

**Comment by seLain** [comment]
My bad. 

It should be 
```python
def delete(self, request, data=None):
!   return json.loads(requests.delete(
        self.url + request,
        headers=self._get_headers(),
        data=json.dumps(data),
        verify=self.ssl_verify
    ).text
```
Using ``requests.delete()`` instead of ``requests.post()``

I'll refine these similar code blocks later.

**Comment by attzonko** [comment]
I'll try and enable the Travis Ci to add the admin tests
