### ISSUE TITLE
dev requirements inside main project

### ISSUE THREAD

**Issue by livestreamx** [attzonko/mmpy_bot#441]
Hi friends.
The question is that - do you really need sphinx and click for application working?
https://github.com/attzonko/mmpy_bot/blob/main/requirements.txt

I guess we can organise better package maintenance for project with Poetry.
Lets do it? I can help.

**Comment by attzonko** [comment]
I have looked at many of the different package managers for Python, but I want to keep this simple like pip 😃 

Many people seem to be using the embedded Click functionality of the application... 

If there are packages you feel are not needed just remove them and put up a PR, here is the one to remove sphinx: #442

**Comment by livestreamx** [comment]
Sorry, but poetry just helps you to keep organised your project. It’s truly easy to use. Just try it)

**Comment by attzonko** [comment]
![standards](https://github.com/attzonko/mmpy_bot/assets/4975715/75a5755a-682d-4028-94d5-2229696550bf)
