### ISSUE TITLE
Legal way to get raw events

### ISSUE THREAD

**Issue by zba** [attzonko/mmpy_bot#483]
**Describe the bug**
I don't find any way to make it correct to handle events for plugins

**How To Reproduce**
In short I wanted  to make llm bot sample with mattermost and wanted to make a feature to regen on recycle reaction, so I tried to find how to get driver's events and not found any good way

**Expected behavior**
A Plugin has a function to call like
```self.subscribe('event_name', callback)``` (which implement for in subscribers call callback somewhere here  https://github.com/attzonko/mmpy_bot/blob/3eb4f346852dd6ee4a14080cc5c80ca184c12ff5/mmpy_bot/event_handler.py#L58)

**Operating Environment (please complete the following information):**
 - mmpy_bot Version: master

**Additional context**
I solved it using this ugly way, but I think it is very bad, 

```
class MyPlugin(Plugin):
    def __init__(self, spy_container):
        super().__init__()
        self.spy_container = spy_container # HERE
    def on_start(self):
        self.bot_instance = self.spy_container['bot'] # HERE
        self.driver.init_websocket(self._handle_event) # plugin handler router handler
    async def _handle_event(self, data):
        event = json.loads(data)
        await self.websocket_event(event) # userspace handler, 
        return await self.bot_instance.event_handler._handle_event(data) # call EventHandler's handler to process messages, etc



spy_container={} # LOOK HERE
bot = Bot(
    settings=settings,  # Either specify your settings here or as environment variables.
    plugins=[MyPlugin(spy_container)],  # Add your own plugins here.
)
spy_container['bot'] = bot
bot.run()
```

**Comment by unode** [comment]
Hi @zba,

For "raw" access you may want to look into [python-mattermost-autodriver](https://github.com/embl-bio-it/python-mattermost-autodriver) which is how mmpy_bot interacts with mattermost.
You can enable `debug` information as described in [usage](https://github.com/embl-bio-it/python-mattermost-autodriver#usage).

If you want to implement conversational behavior in mmpy_bot, see also #140.

**Comment by zba** [comment]
The problem is how mmpy bot handles events, i access driver correct,. Please read example i provide. The problem, that autodriver init songle time, it is not subscription by itself, so mmpy loose connection to driver if i init it in plugin, so i had to make this dirty trick to pass events back to mmpy.

**Comment by unode** [comment]
`mmpy_bot` currently only listens to [`posted` events](https://github.com/attzonko/mmpy_bot/blob/3eb4f346852dd6ee4a14080cc5c80ca184c12ff5/mmpy_bot/event_handler.py#L59).

See #445 for another request to add support for `post_edited` and a suggestion on how to achieve it.
See also #377 and #386 for other discussion about other kinds of events.

Reactions would need a new approach given `@listen_to` doesn't make sense for them.

The point of `mmpy_bot` is that you don't have to interact with events at low level.
If you need that functionality, this is currently not supported without modifying mmpy_bot's source.
We could add support for different kinds of event handlers if a proposal is made and implemented.

Contributions are welcome.

**Comment by zba** [comment]
Yes, i like i haven't too, but why not allow me also raw access as i have access to driver too ? The whole point of this issue is ask to add ability to use functions of driver not implemented in decorators.

**Comment by unode** [comment]
There may be a misunderstanding here. We aren't restricting anything in mmpy_bot.

The driver used by this project and linked above is the core that handles the requests. It supports having one event handler function. This role is taken by the event handler in mmpy_bot.

This handler is not accessible to plugins as this was not part of mmpy_bot's design. If you need access to it, you have two options:

1. Modify mmpy_bot's event handler code to expose events.
2. Use the driver directly, without mmpy_bot and build your own framework on top of it.

If you choose 1, you are welcome to open a pull request with your contributions. Maintainers will review and decide upon it.

**Comment by zba** [comment]
Ah I got, i not neet mmpy bot, because all it does is decorators on posts events, and i can just go with event model without decorators, hm, ok.
