### ISSUE TITLE
Mandatory MATTERMOST_PORT breaks MATTERMOST_URL with subpaths

### ISSUE THREAD

**Issue by yantoz** [attzonko/mmpy_bot#491]
**Describe the bug**
It seems like MATTERMOST_PORT is always used and appended to MATTERMOST_URL and when MATTERMOST_URL contains subpath, the URL becomes invalid

**How To Reproduce**
Specify MATTERMOST_URL with subpath

**Expected behavior**
When MATTERMOST_URL contains subpath, port should be appended before subpath e.g: https://subdomain.domain:port/subpath, instead of https://subdomain.domain/subpath:port
AND/OR,
It is good if the MATTERMOST_PORT can be blank, where no port will be appended at all, in case default port is used (443 for https and 80 for http) 

**Operating Environment (please complete the following information):**
 - mmpy_bot Version: 2.1.4

**Additional context**
Compatibility with MATTERMOST_URL containing subpath

**Comment by yantoz** [comment]
Apparently the problem extends to python-mattermost-autodriver, which mmpy_bot uses.
But I found a workaround for this:

Rather than specifying:

MATTERMOST_URL = https://subdomain.domain/subpath
MATTERMOST_PORT = 443

we can specify below instead:

MATTERMOST_URL = https://subdomain.domain
MATTERMOST_PORT = 443
MATTERMOST_API_PATH = /subpath/api/v4

Rather hacky but works for me.

**Comment by unode** [comment]
This is indeed a known limitation.
Using `MATTERMOST_API_PATH` is the recommended way to configure it but include only `/subpath` not the `/api/v4` part.

```
MATTERMOST_URL = https://subdomain.domain/
MATTERMOST_PORT = 443
MATTERMOST_API_PATH = /subpath
```
