### ISSUE TITLE
Disable httpx logging?

### ISSUE THREAD

**Issue by Roy-Orbison** [attzonko/mmpy_bot#498]
The logs for my bot are most filled with `INFO` level messages like
```
[03/08/2024 14:32:48][httpx][INFO] HTTP Request: GET https://mattermost.example/api/v4/channels/hdjdsjkjsyhyhiiid932ls7jcz/posts "HTTP/1.1 200 OK"
```

Is there a way to log only errors?

**Comment by unode** [comment]
Did you try configuring [`httpx` logging](https://www.python-httpx.org/logging/)?

**Comment by Roy-Orbison** [comment]
Logging is already configured by the bot and I was under the impression that anything I do would either conflict with that or have no effect:
https://github.com/attzonko/mmpy_bot/blob/7b5c6f138ea5afaaaa9324f1f39e2f28ba997cb9/mmpy_bot/bot.py#L83

I don't wish to disable logging entirely, but nor do I need them filled with the (expected) successful requests. The issue is that the settings passed to the bot use a boolean to control an integer log level, which precludes changing the verbosity to `WARN`, `ERROR`, etc.
