### ISSUE TITLE
Python version compatibility issues

### ISSUE THREAD

**Issue by tgly307** [attzonko/mmpy_bot#50]
I've found that deprecated function or module are used(imp module and execfile function). I have replaced these in my own project (Python 3). Does the project consider python version compatibility issues?

**Comment by attzonko** [comment]
With the idea of trying to preserve backwards compatibility with Python 2.7 the only use of execfile I found seems to be protected with a try/except to have it work with both Python 2 and Python 3 correctly.

What was the issue with the imp module?

**Comment by tgly307** [comment]
[Deprecated since version 3.4](https://docs.python.org/3/library/imp.html#module-imp). For the reason that preserve backwards compatibility with Python 2.7, this is not an issue now. Close it?

**Comment by attzonko** [comment]
I still think the issue you bring up for imp is valid. I think we should consider refactoring _load_plugin() to take into account the deprecation. I think we can make it backwards compatible just like we did with execfile with a try/except.

**Comment by tgly307** [comment]
Perhaps we can extract the function involving compatibility, and call the function of the same name of different implementations after judging the environment version. The disadvantage is that the code is not beautiful enough.

**Comment by attzonko** [comment]
Well in my mind the python way to do that is try/except. Eventually I do think we might get to a point where backwards compatibility could get ugly or impractical, but I think we are far from that.

**Comment by tgly307** [comment]
agreed

**Comment by attzonko** [comment]
I'll add Python 2.7 to the Travis Ci check :) Lets keep this issue open until someone has time to refactor _load_plugin()

**Comment by attzonko** [comment]
So the current Travis CI makes sure that the bot works with 2.7 and 3.6 now. I assume eventually the imp module will be truly deprecated and we'll need to solve the problem then.

**Comment by attzonko** [comment]
I updated the Travis CI to check 2.7,3.4,3.5,3.6 I think that should cover us for a while as far as compatibility goes.
