### ISSUE TITLE
How to get displayed channel name

### ISSUE THREAD

**Issue by tilkov** [attzonko/mmpy_bot#535]
Hi,

Currently I am getting the channel name using: 

`
channel = message.channel_name
`

This returns the channel name from the URL, for example 'test-channel'. Is it possible to get the displayed channel name, 'Test Channel' in this case?

Thank you.

**Comment by unode** [comment]
Please use [`driver.channels.get_channel`](https://embl-bio-it.github.io/python-mattermost-autodriver/endpoints.html#mattermostautodriver.endpoints.channels.Channels.get_channel) which given a `channel_id` can return `display_name`.
