### ISSUE TITLE
Please update mmpy-bot in pypi to version 2.2.0

### ISSUE THREAD

**Issue by muirdok** [attzonko/mmpy_bot#551]
**Describe the bug**
It still contains mmpy-bot 2.1.4 and leads to `/api/v4/api/v4/users/me` in requests if install "latest" version via pip.
as workaround could be used:  `MATTERMOST_API_PATH = ""`
```
Name: mmpy-bot
Version: 2.1.3
Summary: A python based bot for Mattermost with its own webhook server.
Home-page: https://github.com/attzonko/mmpy_bot
Author: Alex Tzonkov
Author-email: alex.tzonkov@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages
Requires: aiohttp, click, mattermostautodriver, schedule, Sphinx
Required-by: 
```
looks like in [v2.2.0](https://github.com/attzonko/mmpy_bot/releases/tag/v2.2.0) it's already solved
Many thanks!

**Comment by attzonko** [comment]
Just did, thanks for the reminder.
