### ISSUE TITLE
 About unit test writing

### ISSUE THREAD

**Issue by tgly307** [attzonko/mmpy_bot#58]
I completed the function of uploading files and sending messages with attached files, and manually tested them. But I don't know how to write a test case. Is there a test writing guide?

**Comment by seLain** [comment]
Unfortunately, there is no such guide yet.

Maybe you can check out ``tests\behavior_tests\test_behaviors.py`` , there are two skipped empty tests:
```python
# [ToDo] Implement this test together with the file upload function
@pytest.mark.skip(reason="no way of currently testing this")
def test_bot_upload_file(driver):
    pass


# [ToDo] Needs to find a better way in validating file upload by URL
@pytest.mark.skip(reason="no way of currently testing this")
def test_bot_upload_file_from_link(driver):
    # url = 'http://www.mattermost.org/wp-content/uploads/2016/03/logoHorizontal_WS.png'
    # fname = basename(url)
    # driver.send_direct_message('upload %s' % url)
    pass
```
We have two bots to complete behavior tests. 
The driver bot actively sends message, and expects "correct" response from another bot.
So... maybe the file upload test will be like this:
```python
def test_bot_upload_file(driver):
    driver.upload_file(...)
    driver.wait_for_file_uploaded()
```
You need to implement ``upload_file`` and ``wait_for_file_uploaded`` behaviors in  ``driver.py`` by utilizing APIs you added.

I am not sure if there is any signal comming back from MM server when a file is uploaded successfully. 
If yes, it would be much easier to complete the test by drive bot alone. 
Else we might need the responsive bot to send confirmation message back, and wait for the confirmation message in ``wait_for_file_uploaded()``.

**Comment by tgly307** [comment]
@seLain when a file is uploaded successfully, MM API will return a response which contain file ID and other info about this file, can we test this function this way?

**Comment by tgly307** [comment]
And I checked the doc of MM API, there is no API to upload file by link, we need to download file first and upload them with formData.

**Comment by seLain** [comment]
Yes, I think validating the response with success message should be good enough :)
Do you wanna try to implement the test ?

I'll check the ``upload_file_from_link`` later. This empty test case was migrated from a slack-bot test set before. Indeed this feature might not be supported by MM yet.

**Comment by tgly307** [comment]
In order to maintain the same format as other code, I think the test case needs to be written, but I am not sure if I can write a qualified test case. I will try to write one.

**Comment by seLain** [comment]
Please checkout commit 7b7834f .
I am closing this issue.
