### ISSUE TITLE
message.react doesn't work as expected

### ISSUE THREAD

**Issue by sunnythaper** [attzonko/mmpy_bot#63]
**Describe the bug**
message.react creates a new message in the channel with the specified emoji shown in quote block styling.

**How To Reproduce**
message.react(':joy:')

**Expected behavior**
Expected behaviour is that the message that triggered the event would have an attached reaction from the mmpy_bot. 

**Operating Environment (please complete the following information):**
 - OS: Linux
 - Python Version: Unknown
 - Mattermost Version: 5.2.0
 - mmpy_bot Version: latest
 
**Additional context**
Example of the bug in action: https://cl.ly/3I0f20222I2A

**Comment by sunnythaper** [comment]
Awesome, thank you! I can almost guarantee I messed up and added the colons
haha.

**Comment by attzonko** [comment]
No we had the colons even in the unit test. I thought about adding more code to check for those and strip them, but that could be a future enhancement if we decide it is truly needed.

**Comment by attzonko** [comment]
Merged the fix.

**Comment by knedlsepp** [comment]
There's still one missing: https://github.com/attzonko/mmpy_bot/blob/cd6e7fde3898fe9859d8e5e03c14623eba547135/mmpy_bot/plugins/hello.py#L55
