### ISSUE TITLE
v1.3.2 package fails to depend on schedule

### ISSUE THREAD

**Issue by twilly** [attzonko/mmpy_bot#83]
mmpy_bot v1.3.2 does not appear to depend on [schedule]([https://pypi.org/project/schedule/), which came into being with #68.

Reproduction is fairly straight forward. Create a new virtualenv, pip install mmpy_bot, and try to import a symbol from `mmpy_bot.bot`.

```
$ pip install mmpy_bot
$ python -c 'from mmpy_bot.bot import listen_to'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tristan/tmp/repo/.pyenv/local/lib/python2.7/site-packages/mmpy_bot/bot.py", line 18, in <module>
    from mmpy_bot.scheduler import schedule
  File "/home/tristan/tmp/repo/.pyenv/local/lib/python2.7/site-packages/mmpy_bot/scheduler.py", line 1, in <module>
    import schedule
ImportError: No module named schedule
```

(This should be reproducible anywhere, but in case it matters, I'm running on Ubuntu 16.04.)

**Comment by attzonko** [comment]
I'll leave this open until I make a new PyPi Release.

**Comment by twilly** [comment]
1.3.3 looks good! Thanks for turning this around quicker than I could get to it. :)

**Comment by attzonko** [comment]
Not a problem, can’t have rainbow dash waiting on me 😜
