### ISSUE TITLE
Loading single python module not working

### ISSUE THREAD

**Issue by knedlsepp** [attzonko/mmpy_bot#89]
When I try to define a plugin using a single python module: `custom_plugin.py`, without using a python package (dir + `__init__.py`), using `PLUGINS = [ 'custom_plugin' ]` does not work. The log shows `loading plugin "custom_plugins"`, but no plugin is actually registered.

**Operating Environment:**
 - OS: Linux
 - Python Version: 2.7
 - Mattermost Version: 5.4.0
 - mmpy_bot Version: bc3be35ab76a65bc2ca93f8cee083a966c81ff5a

**Comment by attzonko** [comment]
Can you show the log of the bot starting up and loading the plugins?

**Comment by attzonko** [comment]
@knedlsepp Do you still need help? I am curious what is the error message when it tries to load your module. Perhaps the PYTHONPATH needs to be set correctly? Let us know if we can be of help.

**Comment by knedlsepp** [comment]
There is only this single line of output

**Comment by seLain** [comment]
I think it's a limitation due to how plugin-importing was implemented in  ``mmpy_bot``  right now. 
You need to organize your plugins like this to make them loaded successfully.
```
~/opt/your_bot/
    my_plugins/
        __init__.py
        intro.py
        .....
    local_settings.py
```
@knedlsepp  Is there any reason you have to put plugins in single .py file ?

**Comment by knedlsepp** [comment]
It was the most intuitive way to start off.
