### ISSUE TITLE
Dynamic plugin update

### ISSUE THREAD

**Issue by heliocastro** [attzonko/mmpy_bot#94]
**This is a Feature Request**
I really don't found a prper feature request place, so i took this path.

So, is it possible ( technically speaking ) to have plugins reload in runtime ?

When dealing with external auths and multiple plugin developers, sometimes would be useful rehash the plugin in runtime, at least in development mode.

**Comment by attzonko** [comment]
I think this is a good idea. I will try and find some time to investigate. I do think it is possible, just need to decide what is the best way to do it so it is easy to do. Not sure on a time frame, as I am doing this in my "free" time, but I hope to get some time soon.

**Comment by ralgozino** [comment]
As a workaround, maybe my use case might help. I use the bot running as a (systemd) service and I restart the service whenever I make a change.
Cheers!

**Comment by attzonko** [comment]
I have the same use case, but I think the request is for having different people working on different plugins, and wanting to have them only re-import the single plugin they are working on. I am assuming the individual plugin developers don't have access to restart the service/bot as a whole.

**Comment by heliocastro** [comment]
Start/restart daemon is not an issue.
The issue is that we have one single server running with several developers for the same wide usage bot. 
The developers not necessarily have the admin access to restart the bot itself.

**Comment by seLain** [comment]
I was wondering if we could implement something like [django autoreload](https://github.com/django/django/blob/master/django/utils/autoreload.py).

Developers working on the same bot can sync their code base via VCS/git, and the production bot only checks out code base & reloads at deployment.

**Comment by heliocastro** [comment]
> I am thinking this can be done two ways.
> 
>     1. Add a new setting which when set would have the bot periodically reload all the plugins.
> 
>     2. Add a new setting which when set adds an additional plugin which takes in a string to represent the plugin module name and when triggered tries to reload the passed in module by name.
> 
> 
> I am leaning toward the first option but am open to hear your opinions.

Automatically would not be a good idea. We can't simply calculate a race condition on updating a plugin in the middle of a process. A more accurate idea of what would be ok:
- Code new version
- One of admins ask bot to update plugin xyz
- Bot look if old xyz is not on operation, disable it temporarily, start new one,m reenable it
In the mean time od the restart, a message is put in place that a new version in been updaing

**Comment by attzonko** [comment]
This is now possible with Version 2.x and the ability to call disconnect and the addition of webhook support.

**Comment by jneeven** [comment]
> This is now possible with Version 2.x and the ability to call disconnect and the addition of webhook support. 

This is not entirely true: `driver.disconnect` can be called from any plugin but will shut down the entire bot. But you are right in that with the way Plugins now work, we're almost there. We just need some handles on the EventHandler for registering and deregistering Plugins at runtime, which shouldn't be too difficult. But since this issue is quite old, let's see if anyone still needs this.
