### ISSUE TITLE
Interactive Session with Bot

### ISSUE THREAD

**Issue by sethyes** [attzonko/mmpy_bot#96]
I have an interaction with the bot working, however sometimes the bot returns more characters than my channel will allow. Is there a decorator I can use, or a certain syntax I can use to have the bot wait for a response from the user in the same function? Or does this require a DB etc.. due to being stateful?

**Comment by attzonko** [comment]
I believe it is the later. But you are bringing two different questions.
1. How to handle more characters than the channel can handle.
2. How to handle a multi-stage conversation between a user and the bot

For the first question, the way I have handled it in the past is to break the response down into multiple responses based on character count. 
```
    results = search_results(message, search_terms)
    for item in results:
        message.send(item)
```

For your second question, I did indeed handle it by having the conversation state stored in a DB. But Technically speaking you can have the state stored in a global variable which is part of the plugin module. The issue with that is loosing the state if the bot crashes or gets restarted. 

Hope that helps.
